### ISSUE TITLE
Put a check in on the create listing company retrieval to see if companyId is in fact an array - if not use the only one in the clients profile

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#1002]
As it is right now there is only one companyId. Might be more in the future, but need function to work now as well with only the one companyId :)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/7aa7e896-3df5-413a-b71d-36faff3c0458)

**Comment by Olekrr** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/1005
