### ISSUE TITLE
Documentation - create issue template

### ISSUE THREAD

**Issue by chalund** [NoroffFEU/agency.noroff.dev#1015]
Create a template for creating new issues
Issue #672  is a good model to follow and can help us fix smaller problems more efficiently within the same category
![Screenshot 2024-01-19 at 15 35 03](https://github.com/NoroffFEU/agency.noroff.dev/assets/114383740/58d1250b-ac55-4210-897d-33dc7ece3c89)

**Comment by sulenchy** [comment]
Thanks for your idea. The template has been created. You can check it out at https://github.com/orgs/NoroffFEU/projects/6/views/1?pane=issue&itemId=53355337
