### ISSUE TITLE
Company on create new listing shows client id and not the company name extracted from the companyId from the client profile

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#1018]
Company now shows client id.
It should show the company name of the companyId that is extracted from the Client profile.

Client profile must be fetched, and companyId have to be extracted from this client profile before showing the company name in the input.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/ca484a3f-3f47-408f-8d7e-1228c267a737)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/a370e51a-afd2-4437-8d43-af6b8adbbc05)

**Comment by runeunhjem** [comment]
Not enough time to get this done by the end of Sprint 2, but is a must to fix for the next teams coming later on

**Comment by Tanific** [comment]
Team Phoenix will start working on this issue

**Comment by AbiyuTashoma** [comment]
@MariuszRozycki 
Link to branch: https://github.com/NoroffFEU/agency.noroff.dev/tree/phoenix-createNewListing-displayCompanyNameInsteadOfID

Fixed display correct client company name on create new listing form, other wise functions as before
Save client company name in local storage
On logout clear client company name from local storage data

**Comment by MariuszRozycki** [comment]
@AbiyuTashoma @Tanific @sulenchy  @NoroffFEU/phoenix 

The job is done very well. Very clean and transparent code.
Added comments in the code that explain the changes made.

@AbiyuTashoma can U just remove dead code? Lines in your commit https://github.com/NoroffFEU/agency.noroff.dev/commit/e79a5515af3ee7c1ce1cd713c55fe7291affc442
from 42 to 60. I think it's not necesarry. When it will be removed I will merge it :)

This is question to @Tanific.
Adding listing when the userRole is "Applicant" - I my opinion "Add new listing" in this situation should be hidden, but it isn't our task, so I think we should leave it as @AbiyuTashoma made it :) Do I have a right?


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/55709542/dd89f4f1-f4bd-4171-be3f-873c1f061e80)

**Comment by AbiyuTashoma** [comment]
@MariuszRozycki The commented out old code snippet is now removed. On the other hand you can create an issue/idea regarding the display/hiding of "New listing +" button when user is "Applicant" so that we or somebody else could work on it later on.

**Comment by Tanific** [comment]
@MariuszRozycki Yes you are correct, we will focus on our tasks and if we finish we can suggest new improvements

**Comment by MariuszRozycki** [comment]
@AbiyuTashoma @Tanific @NoroffFEU/phoenix @sulenchy 
Issue nr [#1018](https://github.com/NoroffFEU/agency.noroff.dev/issues/1018) is solved by developer @AbiyuTashoma and merged by QA @MariuszRozycki
