### ISSUE TITLE
Be unable to delete job listings when not logged in

### ISSUE THREAD

**Issue by jonnebonde** [NoroffFEU/agency.noroff.dev#1033]
User that is not logged in are able to delete and edit job listings without being logged in.

**Comment by Tanific** [comment]
Team Phoenix will start looking into this task

**Comment by MariuszRozycki** [comment]
Hei @Mariuskvaal 
Did you created branch on remote repo from phoenix? It looks like commit is only on your local machine. Can U chceck it? I mean, if you are working over any task U should create 'task branch' from our team's branch 'phoenix' as here in docs.  
https://github.com/NoroffFEU/agency.noroff.dev/blob/main/documentation/how-to-branch.md



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/55709542/4907bc0d-ffd8-435f-b9ee-40a1f81d3c6b)


 
Eventually make following steps:
git checkout name-of-your-branch
(if your local repo is not connected with remote repo/if it's is connected U will get: error: remote origin already exists) git remote add origin https://github.com/NoroffFEU/agency.noroff.dev.git
git push origin name-of-your-branch:phoenix

I just can't see another branch created from phoenix.
Chceck it please when U will get time

**Comment by Tanific** [comment]
Yes @MariuszRozycki you seem to be correct, our team will only be merging task branch into team branch, then other teams QA will merge our team branch into main!

**Comment by MariuszRozycki** [comment]
@Mariuskvaal I'm merging your branch with phoenix.

I think you made a god job:
1. You created id for 'delete' and 'edit' buttons in file: pages/listings/listing/index.html
2. Improved function deleteItem and deleteListing insie file: src/js/api/posts/deleteListing.js 
3. Improved function editListingListener inside file: src/js/listeners/post/editListings.js
4. Highlighted changes improved in another files inside: index.js

Every change in files is highlighted by comment. I will not remove those comments. I will leave it for future. It can be helpful for another developers if they will improve your work :)
