### ISSUE TITLE
View listings link on homepage is not linking to the right page

### ISSUE THREAD

**Issue by jonnebonde** [NoroffFEU/agency.noroff.dev#1034]
The view listings page link on the homepage links to a login page, it should probably link to the listings page since it is already available with the listings link in the navbar in the header.

**Comment by rikke-dishington** [comment]
In the isLoggedIn.js file I edited the function isUserLoggedIn() and removed the "else" that made users who were not signed in redirected to the login page. The function now redirects all users to the listings page.
