### ISSUE TITLE
Add a loader/spinner while fetching job listings

### ISSUE THREAD

**Issue by Tanific** [NoroffFEU/agency.noroff.dev#1040]
Create some form of loading indicator to let the user know that the page is loading

**Comment by HGarden** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/1056

**Comment by MariuszRozycki** [comment]
@HGarden The problem has been solved. Now, while all listings are being fetched, users will see a nice loading spinner.

I also suggest adding some comments here (in addition to the new pull request) to explain what was done, just for better communication.
