### ISSUE TITLE
Job listings: Disable search bar until page has completed loading

### ISSUE THREAD

**Issue by Tanific** [NoroffFEU/agency.noroff.dev#1041]
UX: Users shouldn't be able to interact with the search bar until all content has loaded in.

**Comment by JohanLossius** [comment]
Working to fix this. Currently trying to wrap my head around how the project itself works, and then will complete this task properly.

**Comment by JohanLossius** [comment]
Sorted it out now, eventually.
Trying to commit my branch, but getting:
"/usr/bin/env: ‘sh\r’: No such file or directory"

after i git add and commit the relevant files.
No clue how to sort that out.

**Comment by MariuszRozycki** [comment]
@JohanLossius @Tanific @NoroffFEU/phoenix, @sulenchy

First try:
`git add . && git commit -m “name of your commit”`
`git add .` - saves all changes made in all files, U don’t need to write whole path. Git finds the path automatically. 

Second option:
For me @JohanLossius, @Tanific @NoroffFEU/phoenix, @sulenchy  It looks like problem with end-of-line character style.
U can try to solve it in VSC this way:

1. Open the file in Visual Studio Code.
2. Click on the part of the status bar where it says CRLF.
3. Select LF from the list to change the line break style.

@sulenchy Could U look at this message or @Tanific can U contact with @sulenchy and ask is my way of thinkig correctly?

**Comment by Tanific** [comment]
@MariuszRozycki I have forwarded the message to PO!

**Comment by JohanLossius** [comment]
Hello.
@MariuszRozycki @Tanific @sulenchy 
I managed to solve the task itself, and fix the line endings.
Now struggling with the following when trying to commit:
"Git: .husky/pre-commit: line 6: npx: command not found"

Have tried the fixes suggested by ChatGPT, and working with Mariusz currently to figure out how to solve it.

Currently unable to commit my changes based on the above.

Have also sent my changes to the work files to Mariusz, so in worst case, he can create the PR for me/us, so we can get the task completed before the time runs out.

**Comment by JohanLossius** [comment]
Wonderful @MariuszRozycki, thanks a lot! :)

**Comment by MariuszRozycki** [comment]
@JohanLossius @Tanific @sulenchy, @NoroffFEU/phoenix  No problem. Ticket is now moved to DONE :)
