### ISSUE TITLE
Register user

### ISSUE THREAD

**Issue by flanderos** [NoroffFEU/agency.noroff.dev#1049]
Full name is Firstname Lastname format so three or more names are not allowed

**Comment by sulenchy** [comment]
@pkkronborg What is the update on this?

**Comment by pkkronborg** [comment]
Currently on hold. Waiting for project owner to answer what to do with it. It is not a bug, it is according to current scope/design.

**Comment by sulenchy** [comment]
@pkkronborg Thanks for raising this. To fix this, we have to implement other name field on the backend. So the front-end engineers cannot work on it until the backend and the design team do some amendment. We will keep this here for now

**Comment by sulenchy** [comment]
Question resolved. The ticket can stay.
