### ISSUE TITLE
Incorrect Button text - displaying #10005;

### ISSUE THREAD

**Issue by ebejmo** [NoroffFEU/agency.noroff.dev#1104]
A button in the project is displaying #10005; as plain text instead of rendering the intended ❌ symbol. This is due to the incorrect usage of button.innerHTML = '#10005;'; in the JavaScript code. The issue can be fixed by using the proper HTML entity (&#10005 ;)

Steps to Reproduce:

- Navigate to the profile page and click on the 'Edit Profile' button.
- Observe that the button text shows #10005; instead of a meaningful label like X (close).

Expected Behavior:
The button should display ❌ (or a meaningful label) instead of #10005;.

Actual Behavior:
The button displays #10005; as plain text, which is incorrect and confusing for users.

Proposed Fix:
See screenshot attached. 
![Image](https://github.com/user-attachments/assets/710ae2f6-1646-4eb1-83bc-312d318f537c)
![Image](https://github.com/user-attachments/assets/c40541e0-2796-4df6-8f3b-234e13415ad1)
![Image](https://github.com/user-attachments/assets/c45d32bd-883f-4e6c-a399-dd25029871eb)

**Comment by johnsulf** [comment]
Fixed in PR #1106.
