### ISSUE TITLE
Index element "section2" has a margin issue 

### ISSUE THREAD

**Issue by pretzL** [NoroffFEU/agency.noroff.dev#113]
The element with ID "section2" on the index page has a margin issue which causes the content background to be the wrong color.
See image.
![image](https://user-images.githubusercontent.com/30121693/213643793-ee3ef0bc-c45e-4ef3-b551-9268ec55d6b9.png)

The issue is caused by the class `my-2` on the element. This should likely be `py-2` instead, or similar.

**Comment by kmcarlson** [comment]
This seems to be in order, when you check main, so we close this - if someone disagrees, we open this again.
