### ISSUE TITLE
FE-Application HTML || View application - user

### ISSUE THREAD

**Issue by Christonn93** [NoroffFEU/agency.noroff.dev#13]
- [ ] Create markup for viewing application 
- [ ] Add style to match wireframe layout

**Comment by Christonn93** [comment]
@asimenstad How is the task going?

**Comment by asimenstad** [comment]
Just started, but going well so far

**Comment by asimenstad** [comment]
Hi, I just need to make sure I’m using the right wireframe.

This is the one I though I was supposed to use:
[https://www.figma.com/file/HHOtalicJUpQMHBXdbJlOd/Lo-fi-wireframes?node-id=259%3A410&t=9Vi7hKVicYZ8fuzP-0](https://www.figma.com/file/HHOtalicJUpQMHBXdbJlOd/Lo-fi-wireframes?node-id=259%3A410&t=9Vi7hKVicYZ8fuzP-0)


But I just looked through all of the wireframes and found this one:
[https://www.figma.com/file/HHOtalicJUpQMHBXdbJlOd/Lo-fi-wireframes?node-id=542%3A1075&t=9Vi7hKVicYZ8fuzP-0](https://www.figma.com/file/HHOtalicJUpQMHBXdbJlOd/Lo-fi-wireframes?node-id=542%3A1075&t=9Vi7hKVicYZ8fuzP-0)

**Comment by asimenstad** [comment]
@Christonn93

**Comment by Christonn93** [comment]
I will have a look as soon as I'm back from pickup at the school. 
Can't see anything on the links on my phone. 
@asimenstad

**Comment by Christonn93** [comment]
I would say that its both of them. Because one of them is on the admin side, and one is on the student side. 
@asimenstad

**Comment by asimenstad** [comment]
I though the new file was the updated version so I've started on that one. So I should create both of them then? @Christonn93

**Comment by Christonn93** [comment]
I'm asking the design team now :) Will get back to you ?

**Comment by Christonn93** [comment]
@asimenstad 
Response from Design: 
![image](https://user-images.githubusercontent.com/46559129/212314163-faf08425-60fe-4ac6-ba23-b2ce24150e8b.png)

This is the correct one: 
![image](https://user-images.githubusercontent.com/46559129/212314263-c04fc551-dabd-4ae7-a261-a0d36cab3e95.png)
https://www.figma.com/file/HHOtalicJUpQMHBXdbJlOd/Lo-fi-wireframes?node-id=515%3A553&t=CGF861W2U98iWt7p-0

**Comment by asimenstad** [comment]
Great :)
