### ISSUE TITLE
Urgent Login uncaught errors interrupting user testing

### ISSUE THREAD

**Issue by roxannefranco** [NoroffFEU/agency.noroff.dev#177]
These uncaught errors (see details on screenshot below) turn out on cypress test for login.
In order to merge all of my team's changes I need to test those changes first and cannot due to login having these existent errors.
Would be great if this could be taken care of:

![image](https://user-images.githubusercontent.com/50967213/225441623-b900b269-f894-4725-92fb-e1d18aa8af46.png)

**Comment by StianSto** [comment]
the first error originates from js/api/users/getAllUsers.js. the modular function is immediatly executed on line 93, causing it to run once on every single page the file is imported
![Screenshot 2023-03-16 162512](https://user-images.githubusercontent.com/95475303/225666411-0103c50d-225d-4025-8b91-4782c38374b2.png)

I suggest removing line 93 as this is a modular function and should be executed where it is imported in a controlled way. 

ps: might as well move the global querySelector on line 76 inside the function. usersContainer is not being used anywhere else, and we dont need a global variable here.

**Comment by StianSto** [comment]
the second error originates from js/views/admin/deleteUsers.js. it is the same issue as the first error where it is runs on every page, even where "#deleteUserBtn" doesn't exist
![Screenshot 2023-03-16 163556](https://user-images.githubusercontent.com/95475303/225669908-51c7aaff-448f-421f-8c18-6a439b2d07b3.png)

i suggest replacing this timeout with a funciton that adds a listener to a button instead. that way we can control the execution.
rough example: 
```js
function setDeleteUserListener(btn = null) {
  // if no btn is passed in, default to all data-btn-delete-user
  btn ??= document.querySelectorAll('[data-btn-delete-user]');

  // stop if there are no delete buttons in document
  if (!btn || btn.length === 0) return;

  // add listener function
  function setListener(el) {
    el?.addEventListener('click', () => {
      // delete function
      // redirect?
    });
  }
  // add listener (account for single or multiple buttons)
  btn.length ? btn?.forEach((el) => setListener(el)) : setListener(btn);
}
```

**Comment by roxannefranco** [comment]
Hey Stian! Nice caught. Those changes sound ok to me, can you open a new branch and fix it there?
