### ISSUE TITLE
Footer || Styling || (Read comments)

### ISSUE THREAD

**Issue by trine-marie-sandberg** [NoroffFEU/agency.noroff.dev#181]
![Image](https://user-images.githubusercontent.com/91562336/225897605-ca03330d-4747-44e2-8fa3-ad753fed8e9f.png)

**Issues:**
- Pharagraphs moves inconsistently around on different screensizes.
- The styling is not consistent with the current wireframe:
[Link](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?node-id=0-1&t=a7QzIp71ens5AJJQ-0)

**Comment by runeunhjem** [comment]
Outdated - make new ticket if still relevant
