### ISSUE TITLE
Create a md for user flow

### ISSUE THREAD

**Issue by gaznik** [NoroffFEU/agency.noroff.dev#207]

**Comment by DarioDeLaFuente** [comment]
Can this be of help?
Logic flow api endpoit weiw:https://www.figma.com/file/i0RCnWcTigbKr9JKrRuUVe/Site-Map-%2F-User-Flow---Responsive-Component-(Community)?type=design&node-id=2-48&mode=design&t=45oW5WOUDux9PiWg-0

**Comment by runeunhjem** [comment]
Make new ticket if this is still an issue - outdated
