### ISSUE TITLE
Login || Remember Me functionality

### ISSUE THREAD

**Issue by Kenyro** [NoroffFEU/agency.noroff.dev#209]
Remember me checkmark needs functionality to remember user login information.

#### Questions to be answered:
- How should this be stored safely?
- And by what method?

#### Issues that requires resolving:
- Since the ``input`` is part of the ``loginForm`` it likely needs to be excluded from the handler ``setLoginFormListener()`` in ``/api/isteners/``

**Comment by joakimtveter** [comment]
I have this task
