### ISSUE TITLE
FE-Admin || Add functionality to search inputs

### ISSUE THREAD

**Issue by Kenyro** [NoroffFEU/agency.noroff.dev#211]
### Every tab (users, listings, offers and applications) has it's own seachbar, these need JS to function.

- [x] Users - Should be able to search for Name and Email.
- [x] Listings - Should be able to search for Job title, Company and ID.
- [ ] Offers - Should be able to search for Recipient, Company and ID.
- [ ] Applicants - Should be able to search for Applicant, Job title, Company and ID.

**Comment by Kenyro** [comment]
Ilya

**Comment by DrRuski** [comment]
Yes Kenyro?

**Comment by GeniePrinie** [comment]
Note: These already exist in the main branch.

3) Offers - Should be able to search for Recipient, Company and ID.
4) Applicants - Should be able to search for Applicant, Job title, Company and ID.
