### ISSUE TITLE
Homepage || Remove margin h1 on small screen

### ISSUE THREAD

**Issue by Kenyro** [NoroffFEU/agency.noroff.dev#212]
In the wireframes there is no left margin on the homepage h1 so margin needs to be removed on smaller screens in styling
[Figma](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?node-id=122-1884&t=ugx685Ukt2Qhycub-0)

**Comment by GeniePrinie** [comment]
This code still have margin on the h1 in small screen. Still need some fixing :)

**Comment by GeniePrinie** [comment]
New PR was created.
