### ISSUE TITLE
FE-Admin || Close modal - Modal for applicant

### ISSUE THREAD

**Issue by Kenyro** [NoroffFEU/agency.noroff.dev#224]
### This task needs "FE-Admin || Modal for applicant (html)" to have been done first.

- [x] Clicking the "X" in top right corner of the modal should close the modal.
- [x] Clicking outside of the modal should close the modal.

**Check this figma link ->**
https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?node-id=128-1492&t=m1c5UnpACHLOlKpl-0

**Comment by GeniePrinie** [comment]
There's a button on top right corner but it is white, so the user might not be able to see it. But the button works.
