### ISSUE TITLE
FE-Admin || Delete button

### ISSUE THREAD

**Issue by margretheby** [NoroffFEU/agency.noroff.dev#229]
Add functionality to trashcan icon on users, offers and applications tab.
Every listing on the different tabs have its own trashcan icon at the end of the listing.
This icon needs javascript to function.

**Clicking the icon should remove(delete) the listing.
This goes for the tabs users, offers and applications.**

**Comment by runeunhjem** [comment]
Closing this as there is no record of work history since june 2023

**Comment by christerolsen** [comment]
I was working on this.

**Comment by runeunhjem** [comment]
Great, and I apologize, but was not any comments here and no team - could you also choose the team you are on for easier overview.

**Comment by runeunhjem** [comment]
@AnaCascante can you reach out to this guy and tell him to assign team and would not hurt to add a comment on where he is at in progress...
