### ISSUE TITLE
Offer - DELETE - Update tests

### ISSUE THREAD

**Issue by lkmelberg** [NoroffFEU/agency.noroff.dev#235]
- DELETE
  - Admin can delete offers for their company.
  - Admin can not delete offers on another companies applications
  - Incorrect offer id return error status code.
  - Invalid token return error status code.

**Comment by lkmelberg** [comment]
PR: [https://github.com/NoroffFEU/agency-api.noroff.dev/pull/79]

**Comment by runeunhjem** [comment]
Closing this as PR [Feature/offer-delete-test](https://github.com/NoroffFEU/agency-api.noroff.dev/pull/79#top)
#79 above has been closed with unmerged conflicts
