### ISSUE TITLE
Listings page || Style from wireframe

### ISSUE THREAD

**Issue by gaznik** [NoroffFEU/agency.noroff.dev#240]
The listings page template does not look the same as in the hi fi wireframe.
Use the wireframe as a guide and change the relevant code template to match.

**Comment by AnaCascante** [comment]
- [ ] 
- [ ] fikse iconer 
- [ ] 

- [ ]

**Comment by Sovak3441** [comment]
No pull request. Hence no way to test any code.

**Comment by Spookyrumble** [comment]
Is this done? Should the ticket be closed?

**Comment by KarenBonillaM** [comment]
Yes it is done

**Comment by AnaCascante** [comment]
@KarenBonillaM is this issue finished and merged? then it can be closed :) (button under ;))

**Comment by KarenBonillaM** [comment]
Yes it is. Jakob and me worked on the same problem and he merced it

**Comment by AnaCascante** [comment]
ok, I close it
