### ISSUE TITLE
All pages || Tidy opp the heads on all pages

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#243]
All heads in the html files are a bit different with different placing of meta, links and scripts tags. Would look better and more organized if all pages had the same set up in head. 

- [x] All HTML files share a common pattern/template for <head>
- [ ] This is clearly documented for future developers

**Comment by Fermain** [comment]
Hey, what is the desired template for the Head? which page should we use as the canonical reference?

**Comment by Fermain** [comment]
What is the acceptance criteria for this task?

**Comment by Eirik-Haukeland** [comment]
is this a good choice?
there is documentation in the comments, or do we have a different file where we are to document these things?

https://github.com/NoroffFEU/agency.noroff.dev/blob/eecf16bcf1205c9e427f49c220134acf8b875a2d/pages/auth/register/applicant/index.html#L3-L13

**Comment by Eirik-Haukeland** [comment]
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/50040667/15cf9007-9123-4f57-beb3-0a28a1fb0600)

is there a need to have <meta name="author" content="...">?
if there is a need then what am i to sett as the author on all the pages that do not have them all ready?
