### ISSUE TITLE
FE-appplication / offer-views / reject or accept application

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#244]
It can be a good idea to split tasks into separate cards when ready to start working on the page.

- Add JS functionality for buttons
- Add confirmation messages for modal (see Figma wireframe)
- Add modal for accepting an application
- Update styling when design is ready

**Comment by Fermain** [comment]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/10801540/ac0b0d3b-9430-4c4d-926f-6ba300cd85c5)

**Comment by runeunhjem** [comment]
Outdated. Closing ticket. Reopen if needed.
Make new tickets on the issues when issue is being tackled
