### ISSUE TITLE
FE-Listing JS/HTML || Render or create template to display listings in student profile

### ISSUE THREAD

**Issue by DarioDeLaFuente** [NoroffFEU/agency.noroff.dev#245]
The following needs to be updated:

- [x] Key/values matching that of the ``profile/user`` ``API`` response object.
- [ ] Updated logic to handle listing views:
- Proflie company(own)
- Profile company (other)

- [ ] Migrate styling to global scope after agreeing on custom global classes.

**Comment by runeunhjem** [comment]
Fredrik in Holmenkollen is fixing this with tickets 492, 493 and 494, so closing this ticket
