### ISSUE TITLE
Header is missing on home page

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#249]
When viewing the home page, the header element is empty and no navigation can be found:

<img width="439" alt="image" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/10801540/e4f056ed-de3e-4958-b3a0-93568440c5bc">

Suggestion - investigate header rendering script and fix the issue.

**Comment by Martinjens** [comment]
ill look into this

**Comment by Martinjens** [comment]
noticed that, working on a solution for this
