### ISSUE TITLE
Footer is missing on homepage

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#250]
When viewing the site, the footer element is empty and does not include any links etc:

<img width="534" alt="image" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/10801540/23ca5782-d517-4302-afba-8c9fd0403026">

Related to #249

**Comment by mndgs1** [comment]
PR made on https://github.com/NoroffFEU/agency.noroff.dev/issues/253, fixes this issue.

**Comment by Fermain** [comment]
Fixes #249 and #250
