### ISSUE TITLE
Add the 'Edit profile' button to the user profile page

### ISSUE THREAD

**Issue by anasommer** [NoroffFEU/agency.noroff.dev#262]
Add the 'Edit profile' button to the user's profile with styling. 
https://www.figma.com/file/hWJsAz3LDOfLmoYag2zvPS/dekstop-vesrion-for-editing?type=design&node-id=0-1&mode=design&t=Bz1bxoYOdfyMh5Ah-0

**Comment by wexnox** [comment]
um i get This view no longer exists

Select another view to use this project. on this link

**Comment by anasommer** [comment]
Sorry, I don't understand your comment

**Comment by wexnox** [comment]
i tried opening the link

**Comment by anasommer** [comment]
Aaa, I updated the link, sorry
