### ISSUE TITLE
Add the 'Edit profile' functionality

### ISSUE THREAD

**Issue by anasommer** [NoroffFEU/agency.noroff.dev#263]
When the user clicks on the 'Edit profile' button which can be found on the user's profile page, the user will get a form to update the information such as: 

- avatar img
- full name
- title
- degree

Check the [https://www.figma.com/file/hWJsAz3LDOfLmoYag2zvPS/dekstop-vesrion-for-editing?type=design&node-id=0%3A1&mode=design&t=DP59vysf4TXqFlJD-1](Figma) for the detailed design.

**Comment by corrado1982** [comment]
In details this task is about creating a modal after the "Editi Profile" button is clicked?
So it should be an HTML task?

**Comment by anasommer** [comment]
Yes, there will be a modal showing after the button is clicked. But I think that this will require a new separate task for modal.

**Comment by corrado1982** [comment]
Yes, maybe a separate task for the JS of the modal?

**Comment by wexnox** [comment]
i thought the modal was created from line 57

**Comment by anasommer** [comment]
Hmm, seems so, then we just need to activate it. Anyway the separate task would be fine.

**Comment by corrado1982** [comment]
Ok, I didn t see it yet.
I see now that the modal is there.
