### ISSUE TITLE
Cards on listings page

### ISSUE THREAD

**Issue by alexanderdyb** [NoroffFEU/agency.noroff.dev#264]
According to the design in the figma file the cards in the listings page should look like this: 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104794629/2b540032-113d-4ee5-b63c-ec4481754a63)

The frontend looks like this now: 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104794629/f2c33f04-91c8-47a2-bbc1-3705b1b166dc)

Task: Style the cards according to the design.

**Comment by Eirik-Haukeland** [comment]
found one problem the main index.js file looked at the id on the body element to figure out what code to run.

**Comment by Eirik-Haukeland** [comment]
there is more than one styleing for these cards am i to use the one given or make it more like this?
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/50040667/6ff0b799-cb91-431f-ab55-5d8391e5313c)
style-Tile #1 in the [components and style guide](https://www.figma.com/file/QtPHxcxDcEe9QbHDQ926E9/components-and-style-guide?type=design&node-id=10-328&mode=design&t=UfCso9LIUZwhRjsK-0)

the image in the issue have some oddities like the button text is right aligned
