### ISSUE TITLE
Search bar on listings page

### ISSUE THREAD

**Issue by alexanderdyb** [NoroffFEU/agency.noroff.dev#265]
In the design in the figma file the search bar in listings page should look like this: 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104794629/5ab80968-044a-4bf9-8bcf-63ef23a4b6bd)

The search bar on listings page looks like this: 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104794629/ec8eaf92-dcf9-4e01-8af2-14d8e8ac0e1c)

Try to make the search bar look like the design.

**Comment by jakotide** [comment]
![search-input-agency](https://github.com/NoroffFEU/agency.noroff.dev/assets/111381232/d3986dee-fbec-4214-9fea-cc3b352e1d08)

The input field is now responsive and matches the design more.

**Comment by KarenBonillaM** [comment]
Hey @jakotide!

I think you may have overwritten my work 

I worked on this two days ago 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/1f2787cf-92b5-4a0d-96eb-7b4e4213e59c)


This is how it used to look in the desktop version 



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/22b9186f-7431-4b74-8420-df5daeebf90e)

and the mobile version 



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/5db31cd6-e6a5-455c-8ebe-4c573cc5dc7b)

If I open the main branch now. I see the next image:



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/08968515-b8ce-48ea-9fbc-67779d193e5c)

correct me if I'm wrong. Should I change it again?

**Comment by jakotide** [comment]
Hey @KarenBonillaM :)
Yeah it seems we both were working on the same thing! Not sure about the last image you sent tho. After I merged my code to the main branch the live site looked like this:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111381232/e6e6b054-c42e-40f1-b2f2-0ed1fc831b22)

Now it's slightly changed again I see, but as long as it works it's all good!

**Comment by Queenen** [comment]
Opening up this issue again as it currently looks like this:

<img src="https://i.imgur.com/EEi7CQG.png">
<img src="https://i.imgur.com/0y5KjPc.png">

**Comment by Queenen** [comment]
I've made the changes, waiting for a QA to review the changes in this <a href="https://github.com/NoroffFEU/agency.noroff.dev/pull/1026">PR</a>

**Comment by KristianNilsenAug22FT** [comment]
commented and approved PR

**Comment by Queenen** [comment]
PR is now merged, closing this issue.
