### ISSUE TITLE
Home page: view listings btn not working. need href.

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#271]

**Comment by CamillaHorneland** [comment]
<img width="699" alt="Skjermbilde 2023-10-04 kl  13 47 16" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/104870685/3650fede-6575-4067-95fd-c4fa7f4b2abe">

After trying to add href to the btn I discoverd this. I will try to make a function for isLoggedIn to when user press btn i goes to listin page or the login page
