### ISSUE TITLE
All pages: Error. btnDelete is null.

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#272]
Path problem?

**Comment by ebergeng** [comment]
To address this issue, we initially need to modify and refactor portions of the showUsers.js file. Additionally, there's an inconsistency in showListings.js: a button is generated for each listing with an ID of deleteUserBtn. I'd strongly recommend inspecting this before proceeding further.
In the meantime, I'll comment out the line invoking the deleteUser() function

**Comment by jkjode** [comment]
I'll create a new issue for "showUsers.js" and we'll put the btnDelete.js on hold for now @ebergeng

**Comment by ebergeng** [comment]
perfect :)

**Comment by ebergeng** [comment]
I don't think I can start on this before #285 is merged, as I'll be working on some of the same files. This might result in a merge conflict, right?

**Comment by jkjode** [comment]
#285 is completed and merged @ebergeng

**Comment by ebergeng** [comment]
Added an event listener to the delete buttons, which sends a request to the dummy API to delete the user.

I don't think the next step in the flow has been designed yet. For instance, will there be a modal popup to confirm the delete request
