### ISSUE TITLE
All pages: Why id on body: hompage/ or homePage.

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#274]
Should be another name or dosent matter?

**Comment by Nilliz85** [comment]
I've investigated the issue, and it appears that there's a situation where several pages in the codebase have the `<body id="homePage">` attribute. This could potentially lead to issues as the body ID is commonly used in the router functionality.

Additionally, I've noticed some discrepancies in the router functionality:

- Some IDs are not being applied as expected.
- As mentioned several pages have the `homePage` ID. which can cause routing issues

To address this, I plan to do the following:

1. Review the router configuration to ensure that all pages have appropriate IDs, avoiding the duplication of the `homePage` ID.
2. Identify and correct the instances where the IDs are not being applied correctly in the router functionality.


I'll work on resolving these issues to ensure the proper functioning of the application. If you have any specific suggestions or additional details, please feel free to share them.

**Comment by jkjode** [comment]
Created an issue for bot i and ii as per your comment @Nilliz85 . I'll put this one back in the "To do" list and assigned you to both new issues, with #286 put under "Doing" for now. When this is resolved you can get on with #287 before coming back to this one.

**Comment by jkjode** [comment]
#286 and #287 were created from this, but solving these has also left this solved as a result. Considered closed
