### ISSUE TITLE
FE-Application HTML  || Carousel Homepage

### ISSUE THREAD

**Issue by Christonn93** [NoroffFEU/agency.noroff.dev#28]
- [ ] Create markup for bootstrap carousel for listing cards
- [ ] Add style to match wireframe layout

**Comment by Knirkeli** [comment]
@KarenJoo This seems like one to delete? Cant find a carousel on the home page in the design. There is one in for the listings Should we create a new for that?

**Comment by KarenJoo** [comment]
@Fermain what is the status on this issue? This is a issue created in January 2023, I see kribach12 removed it from the Frontend Team board but it was restored 3 days ago?

**Comment by runeunhjem** [comment]
Closing this for cleanup purposes - reopen if needed, or make new ticket if still an issue later on
