### ISSUE TITLE
Repo || Configure Vite

### ISSUE THREAD

**Issue by Eirik-Haukeland** [NoroffFEU/agency.noroff.dev#281]
The Setup is a mess and needs to be cleaned up.

- [x] Configure Vite to compile the SCSS and enable dev source maps
- [x] Configure Vite with every possible entry point to the app
- [x] Document the procedure to add new entry points in the `readme.md`
- [x] Clean up the scripts in `package.json` removing the unnecessary once
- [x] Update the `readme.md` to reflect changes

**Comment by Eirik-Haukeland** [comment]
when this is done do we still need jest? 
or can we add "remove jest" to the todo-list

**Comment by mndgs1** [comment]
Talk to Scrum master about this issue? I can fix it, since I am already fixing the build pipeline.
