### ISSUE TITLE
Create listing: If filling out wrong get a modal box with an X.

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#284]
But it do not close when pressing the x - just outside the modal. Should close pressing X also.

**Comment by Spekkhogger** [comment]
After checking the code, it seems the X is not really supposed to function as a exit from the modal, but rather a indication something went wrong -> it has a success counterpart with a checkmark instead of an X. 
I think the dismiss/close label should be added to both, or neither
