### ISSUE TITLE
modify and refactor portions of the showUsers.js file.

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#285]

**Comment by ebergeng** [comment]
Made a new version of the showUsers.js file. The butten is now generated with a unique id, ready for eventlisteners on click.

Also comment out a few lines of code like deleteUser() in adminRouter.js and setDeleteListingListener(jobId) in line 50 in showListings.js. Threse functions are not ready to be used yet and only cause problems when we try to use them.

**Comment by ebergeng** [comment]
Found an issue with the import: import { getToken } from './getToken';
It should be: import { getToken } from './getToken.js';
