### ISSUE TITLE
Review the router configuration to ensure that all pages have appropriate IDs, avoiding the duplication of the homePage ID.

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#286]

**Comment by jkjode** [comment]
This issue has been impacted by #292 aswell. Not life-changing, but impacting

**Comment by jkjode** [comment]
Issue digs deeper than initially thought and might have to be split into smaller issues to be handled seperatly.
@Nilliz85 has been digging and we will debate further action towards this in todays meeting

**Comment by jkjode** [comment]
@Spekkhogger and @CamillaHorneland will jump on and continue working with @Nilliz85 on this issue

**Comment by Spekkhogger** [comment]
For singleApplication I've found two separate functions. One that calls on the dummyAPI and another that looks unfinished. I'm adding in the dummyAPI one for now.

**Comment by jkjode** [comment]
Great teamwork guys!
