### ISSUE TITLE
Duplication of code and confusing code

### ISSUE THREAD

**Issue by MagnusPladsen** [NoroffFEU/agency.noroff.dev#304]
In the index.js file showListing() from views/admin/ is being called two different places AND inside adminRouter() also. 

So why are this function bein called in so many different places. 

<img width="671" alt="image" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/93226629/fa68b903-eed2-4725-a07b-b9b12c0da48b">

Line 44 har adminRouter which looks like this:
<img width="344" alt="image" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/93226629/84fc9c81-3602-4698-85e1-49a4c386fe30">

<img width="689" alt="image" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/93226629/90785882-f0a7-4b6a-980b-25fa46a823af">

**Comment by MagnusPladsen** [comment]
I belive the problem is that there are duplicates here and way too confusing names for the listings pages. 

singleListing is probably for one listing?

But is not listing also for one listing? By the end of line 55 it looks like maybe listing is for multiple listings.

But case listings looks like its for job listings.

And case listingsPage is for another job listings page?

"listing" and "listingsPage" are calling the same and settings the same.

**Comment by MagnusPladsen** [comment]
I think line 54 is for the multiple listings and should maybe have the case/ID as listings. 

And line 60 "listings" should be something else to not interfere with the naming.

**Comment by mndgs1** [comment]
this needs restructure for sure, http://127.0.0.1:5173/pages/listings/index.html has body.id = "listing". I think we need to separate the API functions from HTML Builders. 
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/64353317/83ab7516-3b7a-482c-9ec1-355ce9c66f57)
I took a look at the functions they are calling. Rename these functions, make them call the same api function. And start adding docs to functions so people could reuse them more easily?

**Comment by idanguyen** [comment]
it seems like the title in TBD listing dose not update. I found out that it used ID listingsPage. I therefore deleted duplicate listings. I also rename listing to listings. 

In the future listingsPage should be renamed when TBD is named to fit.
