### ISSUE TITLE
Home link in navbar missing

### ISSUE THREAD

**Issue by alexanderdyb** [NoroffFEU/agency.noroff.dev#310]
In the figma files it is a "Home" link in navbar:

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104794629/b1badbc4-b3e1-42ff-ad42-b31a3b7cbf0c)

**Comment by Martinjens** [comment]
Ill look into this. Is this something that should be added throughout all of the pages ? exluding the homepage

**Comment by alexanderdyb** [comment]
@Martinjens Here is the figma files: https://www.figma.com/files/project/78324144/agency.noroff.dev?fuid=1289550312947202806

The "Home" link is not on the register and login page, but on all other pages.

**Comment by Nightfox77** [comment]
Checked the site, the HOME link is visible and working. This issue can be closed @KariannNor
