### ISSUE TITLE
the registerUrl

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#315]
apiUrl + action apiUrl ends with a / and the action variabel starts with a / , that equals to "https://api.noroff.dev/api/v1/mabye//auth/register". Mabye thats the reason why you cant fetch the registerUrl

**Comment by JonnyNewfarm** [comment]
I have changed the action variable to 'auth/register' but its still not able to fetch. I am looking further into the problem

**Comment by JonnyNewfarm** [comment]
api/v1/auth/register does not exist


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/79f7593e-8d56-4c7e-b414-549549c3f5c6)

I can see that they have used another api to login 
https://dummyjson.com/docs/auth/login

I will try to use dummyjson api to register user
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/2017dc26-3cc9-4279-9b47-16dc87fc9d82)

**Comment by JonnyNewfarm** [comment]
I am not even able to log in with the dummy api using the right credentials


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/0bf21562-301e-48e8-b5f3-ab8a264e47c0)

**Comment by saibia8** [comment]
I think you should use this url:  
https://agency-api.noroff.dev/users

And you can read more about agency API: https://agency-api.noroff.dev/api-docs/#/Users%20Authenticate/post_users

**Comment by jkjode** [comment]
I think this issue should be kept to the original task and communicate other findings to be opened as new issues at a later point. Maybe work further on one or more of those on a new or leave it for the future. 

Issue #315 itself has been resolved
