### ISSUE TITLE
pages/admin

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#316]
When script and link on all pages was changed the li elements changed from grey to green. Not very good readability.

**Comment by Emilyrf** [comment]
![Captura de Tela 2023-10-10 às 12 54 13](https://github.com/NoroffFEU/agency.noroff.dev/assets/104759694/0fb94239-7504-4cb3-b901-45219e1a9954)

**Comment by CamillaHorneland** [comment]
PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/336 . 

I see several files not added as well. Maybe open a new issue on this? This is for profile page and auth.

 I would also want to change the naming on some of the folders i scss folder to all start with "_" before name exept for the index.scss files.
