### ISSUE TITLE
Public Folder/assets and images

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#318]
Looks like the assets folder has been moved. Icons are not showing and so it seems links have been rendered obsolete. 

Check if the assets folder has been moved and have a look at the links throughout the repo.

If this is true, let me know and we will convert this to issue.

**Comment by Nilliz85** [comment]
Have found and fixed most ./assets pathway to ./public/assets as someone moved the folders and the icons stopped working.

when I'm done fixing those i will do the same for the image folder which was also moved to the public folder.

**Comment by Nilliz85** [comment]
Done fixing all the images and assets filepaths to include the public folder

All the filepaths should now be fixed and work as intended.
