### ISSUE TITLE
Mobile: Listings page small css adjustmens

### ISSUE THREAD

**Issue by anasommer** [NoroffFEU/agency.noroff.dev#334]
relates to #333 
Make small adjustement to mobile design, so the Listings page will look like figma design:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/68922341/a4e086a4-a314-48d0-9c1a-990e6ae66ebc)

**Comment by wexnox** [comment]
Bug on build. cant style until fixed

**Comment by KarenBonillaM** [comment]
When working on the Listings page issue #240 I also check the mobile version

**Comment by KarenBonillaM** [comment]
@MHerholdt94 Hey!
I took this issue since it relates to issue #240 listing page styling.

Ana told me to let you know

Fyi
