### ISSUE TITLE
Header and footer styling is missing

### ISSUE THREAD

**Issue by ritugunjan** [NoroffFEU/agency.noroff.dev#345]
When opened in live server, a lot of header and footer styling is missing

**Comment by wexnox** [comment]
Can you provide us with an image?

**Comment by ritugunjan** [comment]
[Screenshot.docx](https://github.com/NoroffFEU/agency.noroff.dev/files/12869625/Screenshot.docx)

**Comment by ritugunjan** [comment]
Also, the image on the home page is not responsive
[Screenshot.docx](https://github.com/NoroffFEU/agency.noroff.dev/files/12869650/Screenshot.docx)

**Comment by corrado1982** [comment]
Seems like working on mine...
Using live server there is a problem with logo and some icons, but is responsitive and I can see header and footer...
![Immagine 2023-10-11 143432](https://github.com/NoroffFEU/agency.noroff.dev/assets/104769882/cb507a96-8c2c-4c02-a675-b315796a710b)
![Immagine 2023-10-11 143510](https://github.com/NoroffFEU/agency.noroff.dev/assets/104769882/c3a2c9a4-5ce7-470b-ac18-06fd0b65f1bc)

**Comment by anasommer** [comment]
Did you start live-server that is built in VS code or ran a command in the terminal?

**Comment by CamillaHorneland** [comment]
I think it´s beacuase om this pr https://github.com/NoroffFEU/agency.noroff.dev/pull/327. In lockahost it works linking to dist folder but on this you see in console it cant find it. https://agency.noroff.dev/

**Comment by ritugunjan** [comment]
@anasommer I started it in the live-server in VS code

**Comment by bLangved** [comment]
What is the status on this issue? 
I see the sames issue on the build I'm watching here: https://agency.noroff.dev/
- I can work on it if it was not completed :)

**Comment by zalacop** [comment]
hey, from what i see the footer looks correct now, and the header the hamburger menu icon is not aligned

**Comment by bLangved** [comment]
I will fix the header then. Thx for quick reply, @zalacop

**Comment by bLangved** [comment]
Even though padding and gap distance between elements in footer are a little off compared to figma files, but that can be another issue

**Comment by zalacop** [comment]
I can start on that issue

**Comment by bLangved** [comment]
Yeah, I was refering to the gap-distance of the list elements, and the distance between browser border and elements in the footer (at least on mobile view). Kind of looks good on desktop, compared to figma. 
If you open a branch on this, consider calling it #345-2-something, since I allready have a branch with that issue number :)
@zalacop

**Comment by zalacop** [comment]
Yeah sure I can do that =), thanks =)

**Comment by bLangved** [comment]
#672 : Header - HTML, styling & script 

The header got a new issue, since this was not specific enough.

**Comment by bLangved** [comment]
I will mark this issue as done, since we are moving over to seperate issues. This one was overly vague. 

New issue for HEADER: https://github.com/NoroffFEU/agency.noroff.dev/issues/672 : Header - HTML, styling & script
