### ISSUE TITLE
index HTML || the image in the Hero Section is missing

### ISSUE THREAD

**Issue by karolina-szymanska** [NoroffFEU/agency.noroff.dev#348]
The banner image in the Hero Section is missing. Inspected it here: https://agency.noroff.dev/ and I see the styles are gone.
This might have something in common with #337 and #346 which say: SCSS issues across the pages.

**Comment by CamillaHorneland** [comment]
I think it´s beacuase om this pr https://github.com/NoroffFEU/agency.noroff.dev/pull/327. In lockahost it works linking to dist folder but on this you see in console it cant find it. https://agency.noroff.dev/ to dist but on
