### ISSUE TITLE
NAV items in mobile view

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#349]
Needs to be centered

**Comment by Emilyrf** [comment]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104759694/cabb6855-1be9-434b-818d-d7e433221d85)

**Comment by JonnyNewfarm** [comment]
##I fixed the hover state on the items

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/52a10460-746d-4a6f-93fe-775824fa8c83)

##After

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/291b80be-59ab-49f2-9a04-15e6a5b7d195)

##Then i aligned the items in the center and added some padding on the top an bottom


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/bf266006-8460-4151-9457-761205079816)
