### ISSUE TITLE
Register - refresh when submitting the form

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#350]
When submitting the registration form, there is a page refresh and it isn't clear if the process succeeded or failed. Please investigate the timing on this page.

**Comment by saibia8** [comment]
Adding to pages\auth\register\applicant\index.html page:



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/805ddd16-a975-4edd-8b1b-c9fb438d17e6)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/3eee1083-b84b-4f37-b840-93317f508e42)

I was then reading from the input Full Name value, creating firstName and lastName strings, and inserting them into the profile object.


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/00cac03f-cd19-477b-a3cb-6f773257bf09)

The object is created and sent to the register function:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/010a1b2b-4386-4ebe-bc4b-90c3f91bfbf8)

Sending data to fetch and if its error displays error, if no errors display success message:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/07b5939a-eef0-4a67-aaf8-f39578db78b8)

**Comment by saibia8** [comment]
Then I tried to test it from my local computer I got errors:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/22fef11f-8717-4a03-8658-3b48f1caafef)

I am sending data: 


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/c2860ff8-72cc-4169-911a-b063788c74cc)

I am getting headers:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/b5dce31d-4892-4fe8-aa4f-1020d8e97eae)


Then I try the same API call in https://agency-api.noroff.dev/api-docs/#/Users%20Authenticate/post_users, and I get the response ok: 


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/dc6308c3-cf16-47c3-939d-e1dfcc4fba1f)

What is the problem?

**Comment by saibia8** [comment]
I got a suggestion to use https://cors.noroff.dev/ in front of the request URL and it worked.  Just it makes the URL very ugly 🙂.



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/a47491e8-c210-42eb-bb71-b0da60d10668)


Successful registration message shows if it is no errors:



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/080b66fb-0149-49c9-aeff-87fdd9da2682)
