### ISSUE TITLE
Home page has incorrect stylesheet link path

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#352]
CSS is now in root/css not root/dist/css

**Comment by CamillaHorneland** [comment]
PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/366

**Comment by CamillaHorneland** [comment]
Now links to stylesheet outside dist. 
Another way to do this is to delete the css files outside of dist. Link all stylesheets in html to dist instead and add this code to package.json as well.
