### ISSUE TITLE
Listings page 404 on live, not on local

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#354]
The listings page (may affect other pages too) shows a 404 error on the live site: https://agency.noroff.dev/pages/listings/index.html
But not locally: http://127.0.0.1:5173/pages/listings/index.html

I suspect that this is webserver configuration issue that can be solved with a `_redirects` file: https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

**Comment by Spookyrumble** [comment]
Relative path issue. Changed paths to listings, search icon and Noroff logo

**Comment by Sovak3441** [comment]
Which issue is this related to ?

**Comment by Spookyrumble** [comment]
It was an issue on the board. I just grabbed it. It reads 354 on the PR :)

**Comment by Sovak3441** [comment]
I cant seem to find a issue with the same name. Have there been added an issue for it?

**Comment by Sovak3441** [comment]
issue resolved from other
