### ISSUE TITLE
Navbar component for mobile devices is not implemented  

### ISSUE THREAD

**Issue by DarioDeLaFuente** [NoroffFEU/agency.noroff.dev#357]
NavBar and drop down menu is not responsive/ implemented on mobile screen.

[**Figma wireframe for guidance.** ](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=0-1&mode=design&t=w3g2HkBcP2XMo5or-0)
<img width="910" alt="Screenshot 2023-10-11 at 19 58 13" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/e19abeb4-cdc8-4244-b294-bdb95fc3582e">

**TO DO:**
- [x] The logo and hamburger menu should be contained at a certain width.
- [x] Buttons in the dropdown menu are disproportionate.
- [x] Liks NOT centered.

**Local wei:**
<img width="353" alt="Screenshot 2023-10-11 at 20 52 59" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/fa93a20f-7fb1-4720-8d0b-fdbaa6dcc71c">

**Use:**[Offcanvas navbar](https://getbootstrap.com/docs/5.1/components/navbar/#)
Offcanvas
Transform your expanding and collapsing navbar into an offcanvas drawer with the offcanvas plugin. We extend both the offcanvas default styles and use our .navbar-expand-* classes to create a dynamic and flexible navigation sidebar.

In the example below, to create an offcanvas navbar that is always collapsed across all breakpoints, omit the .navbar-expand-* class entirely.

**Info:**
 "dependencies": {
    "bootstrap": "^5.2.3",
    }
    
    **Steps to create offcanvas menu from Bootstrap navbar component for mobile devices**
Using this method, you can turn any card into offcanvas on mobile screen.

1. Create basic bootstrap navbar
2. Add your class to navbar element controll it. For example mobile-offcanvas,
3. Add media query into your css file, add custom styles to you navbar for smaller screen size, then make it invisible with transformX(-100%)
4. Add button on your website to show / hide your navbar.
5. Now create two functions like function close_offcanvas(){ .... } and function show_offcanvas(){ .... }, add some code that adds/removes class based on click.
6. Add another styling for .offcanvas-mobile.show to make it visible by adding opacity:0, visibility:visible and transform(0)

**Comment by zalacop** [comment]
this also seems like it's been fixed already

**Comment by AnaCascante** [comment]
@zalacop is this issue finished and merged? then it can be closed :)
