### ISSUE TITLE
for attribute in the form on pages/TBD/index.html is wrong

### ISSUE THREAD

**Issue by Eirik-Haukeland** [NoroffFEU/agency.noroff.dev#360]
# the issue

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/50040667/48219335-75a1-4d45-906f-1ae50c7a980b)

the for attribute in the label (1)  is set to the value of the name attribute(3) on the corresponding input field but for proper functioning it must be sett to the id attribute (2)

# proposed solution
change the for attribute on the labels for

- [ ] [Contact Person (link to line)](https://github.com/NoroffFEU/agency.noroff.dev/blob/main/pages/TBD/index.html#L32)
- [ ] [Email (link to line)](https://github.com/NoroffFEU/agency.noroff.dev/blob/main/pages/TBD/index.html#L37)
- [ ] [Phone Number (link to line)](https://github.com/NoroffFEU/agency.noroff.dev/blob/main/pages/TBD/index.html#L42)
- [ ] [Offer Text (link to line)](https://github.com/NoroffFEU/agency.noroff.dev/blob/main/pages/TBD/index.html#L52)

page: https://github.com/NoroffFEU/agency.noroff.dev/blob/main/pages/TBD/index.html

**Comment by maazshakeel** [comment]
Can I get assigned?

**Comment by maazshakeel** [comment]
Made a pull request
https://github.com/NoroffFEU/agency.noroff.dev/pull/361
