### ISSUE TITLE
Navbar differences from Figma file

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#365]

**Comment by JonnyNewfarm** [comment]
Change to a cross to close when navbar in mobileview is open like in figma



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/506930ac-6e33-4fbf-9491-636b4a45b91e)

**Comment by JonnyNewfarm** [comment]
hamburgermanu trasitions to an x when opened

Closed state
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/7f300375-bc19-4481-9a53-fdaa00c9b22f)

Open state

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/92221775/b8769875-cfd1-4867-9fe3-27e3d7eb8ef9)
