### ISSUE TITLE
/TBD/listings.html not rendering listings correctly

### ISSUE THREAD

**Issue by Nilliz85** [NoroffFEU/agency.noroff.dev#368]
I've noticed that the "/TBD/listings.html" page is not rendering the listings correctly.

From my observation, it seems that the listings from the API are not being imported correctly, resulting in plain text instead of following the expected styling structure as seen in the placeholders.

I will investigate this issue to ensure that the listings are displayed as intended.

**Comment by Nilliz85** [comment]
Changed the HTML implementation that existed in the showListings() function. So that the Listings rendered from the API looks more like the placeholder design, the placeholders are to small to fit all the information so the size is not consistent through the listings. this should be looked at if this page is to be moved from the TBD folder.

this changes was first mistakeingly added through the [318-assets/icons] branch
(https://github.com/NoroffFEU/agency.noroff.dev/tree/318-assets/icons)

**Comment by jkjode** [comment]
Issue resolved, just leaving it hanging until comments have been added for future reference
