### ISSUE TITLE
listings - needs gap between the cards

### ISSUE THREAD

**Issue by kmcarlson** [NoroffFEU/agency.noroff.dev#379]
<img width="915" alt="image" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/77496513/9da53041-b47e-43bf-a41d-4ed37a805813">

The content is centered, but i needs gap between the cards

**Comment by corrado1982** [comment]
Hi, with the style you added it put everything in one column instead of 2...
it can be some other way to fix it mantaining 2 colunms?
