### ISSUE TITLE
Styling Cards || Should have shadows?

### ISSUE THREAD

**Issue by corrado1982** [NoroffFEU/agency.noroff.dev#390]
On the Figma draw there is not shadows of the cards or containers..

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104769882/177c4761-5570-4d94-baee-dc7e59b17ccb)

But in some pages some developers used...

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/104769882/464b1e96-c75b-4b35-80b4-fbaaa2cc1aae)

Is it a good idea to update the Figma draw with shadows?
So the future developers will know when use it...

**Comment by Bjonne696** [comment]
changed name on branch to 390-styling-cards-should-have-shadows, encountered this error, with the name of the issue:

fatal: cannot lock ref 'refs/heads/390-styling-cards-||-should-have-shadows': Unable to create 'C:/Users/Bjonn/OneDrive/Dokumenter/GitHub/agency.noroff.dev/.git/refs/heads/390-styling-cards-||-should-have-shadows.lock': Invalid argument

this was fixxed by removing || in the name.

**Comment by Bjonne696** [comment]
From what i can observe, the figma board seems to allready have been uppdated. And shadows are placed correctly according to the board.
