### ISSUE TITLE
Mobile: Footer text alignment

### ISSUE THREAD

**Issue by John5en** [NoroffFEU/agency.noroff.dev#392]
The text in the footer needs to be moved to the left a bit, right now it is centered.
Figma mobile prototype: https://www.figma.com/file/uBKNiiJMJJTUEXZGfAX1Vs/mobil-version-for-editing?type=design&node-id=0-1&mode=design&t=HWVUKU8AbkbHMVUh-0

How it is now:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/105588828/7e82080b-31b0-44a4-837d-664f965d0871)

How it should look:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/105588828/dde27288-9993-4b6f-9957-e303ba4fc899)

**Comment by zalacop** [comment]
hey, this seems like it's already done.

**Comment by AnaCascante** [comment]
@zalacop is this issue finished and merged? then it can be closed :)

**Comment by zalacop** [comment]
it's done with issue #345, it's been merged
