### ISSUE TITLE
Fix warning in DEV mode

### ISSUE THREAD

**Issue by MagnusPladsen** [NoroffFEU/agency.noroff.dev#393]
Getting this warnings in dev mode. 

To repricate: 
`npm install`
`npm run dev`

This warnings are getting logged in the console:

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/93226629/9a4f246d-9f9a-4baa-8fc4-01436eb17187)

**Comment by jonnebonde** [comment]
I have changed the paths for the assets and made a pull request for this issue.

**Comment by Bjonne696** [comment]
There was a conflict with the "pages/listings/index.html". This was probably caused by this beeing a "old" issue. Conflict was resolved and merged succsesfully
