### ISSUE TITLE
Sign in with wrong credentials shows "unknown" error

### ISSUE THREAD

**Issue by MagnusPladsen** [NoroffFEU/agency.noroff.dev#395]
Sign in with wrong credentials shows "unknown" error instead of the actual error message from the API. The text should be replaced with what error the API returnes.

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/93226629/f587a921-f5cd-4305-a7f9-d47ed309e582)

**Comment by Spookyrumble** [comment]
Added email verification functionality to block fetch with wrong format email.

**Comment by Spookyrumble** [comment]
This issue has been resolved elsewhere. It shows in the conflicts. I think this can be safely discarded.
