### ISSUE TITLE
Bugfix Bild error.

### ISSUE THREAD

**Issue by DarioDeLaFuente** [NoroffFEU/agency.noroff.dev#397]
The Bild is getting an error on missing scss

**Comment by CamillaHorneland** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/issues/400

**Comment by DarioDeLaFuente** [comment]
@CamillaHorneland  comment out incorrect imports oss scss file ref:https://github.com/NoroffFEU/agency.noroff.dev/issues/400
YES.
<img width="764" alt="Screenshot 2023-10-15 at 22 13 05" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/5f6f7ffa-9da4-44f7-8fb8-1cd166053db2">

**Comment by DarioDeLaFuente** [comment]
@ritugunjan can u approve this PR
