### ISSUE TITLE
Registration form and login in Modal ? 

### ISSUE THREAD

**Issue by Baporek** [NoroffFEU/agency.noroff.dev#399]
Should the Registration form and login be as the modal window ?

**Comment by MHerholdt94** [comment]
Is there an updated wireframe that calls for this? Or is it only a suggestion?

**Comment by runeunhjem** [comment]
Assigning this to Korketrekkeren wich have login/registration Sprint 2

**Comment by kimrm** [comment]
I don't really see the need to have this in a modal?

**Comment by kribac12** [comment]
@NoroffFEU/korketrekkeren Does anyone think this should be in a modal, or should I close the issue? 
@kimrm @AndreasYager @EM-90 @LineNil @ellie489 @mhaarseth

**Comment by mhaarseth** [comment]
I didn't really understand what this was about, to be honest.

**Comment by EM-90** [comment]
What is it about? because both login and registration are modals

**Comment by kribac12** [comment]
As of now the forms are just containers, and there was a suggestion about making them modal windows, and I was wondering if any of you saw the need for that. @EM-90  @mhaarseth

**Comment by LineNil** [comment]
I vote for closing the issue. @kribac12
