### ISSUE TITLE
Implemented build test as a status check

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#402]
Use github actions to test whether the repo can be built, and set this as a status check. This way the live site will not be deployed when the build is broken.

**Comment by DarioDeLaFuente** [comment]
To add a check in the workflow to ensure that the code is in a good state before deploying, you can use a conditional check based on the result of a script or a command. In this case, you might want to use a step that checks the code quality and only proceeds with the deployment if the code is in a good state. One common tool for this purpose is a linter. You can use a linter to check your code for issues and only deploy if the code passes the linting checks.

yaml feil

`name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Lint Code
        run: |
          # Add the code linting command here
          # For, eslint or stylelint
          # If the linting fails, the workflow will stop
          if ! npm run lint; then
            echo "Code linting failed. Deployment canceled."
            exit 1
          fi

      - name: Build CSS
        run: npm run build

      - name: Build Vite
        run: npm run vite-build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1`


In the modified workflow:

A new step named "Lint Code" is added after the code checkout and before the build steps. This step runs a code linting command (e.g., npm run lint) to check the code quality.

If the code linting fails (returns a non-zero exit status), the step will echo an error message and exit with a status code of 1, which will prevent the subsequent deployment steps from running.

If the code linting succeeds, the workflow proceeds with building and deploying the static content.

This way, the workflow will only deploy if the code passes the linting check, ensuring that the don't deploy code that doesn't meet the specified code quality standards.

**Comment by kyrregjerstad** [comment]
Completed in https://github.com/NoroffFEU/agency.noroff.dev/pull/571
