### ISSUE TITLE
Missing file extension in showUserDetails.js

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#403]
This causes a 404 on the live site, as the webserver looks for an HTML file instead of JS:

`import { userDetailsTemplate } from '../../templates/profile';`

This can be fixed with:

`import { userDetailsTemplate } from '../../templates/profile.js';`

**Comment by DarioDeLaFuente** [comment]
This is solved i this pr : [Updated the dummyApiUrl to apiPath and clean up out commented things #406](https://github.com/NoroffFEU/agency.noroff.dev/issues/406)
@Bjonne696
