### ISSUE TITLE
QA - Create a list of every function that uses the Dummy API URL

### ISSUE THREAD

**Issue by Fermain** [NoroffFEU/agency.noroff.dev#404]
There are a number of files that are still using the Dummy url, please change these over to the production / testing API url.

**Comment by ESPR07** [comment]
The getListOfListings function in getListofListings.js (src -> api -> posts) file is still using the dummy url,
as well as
The getSingleListing function from getSingleListing.js (src -> api -> posts) file is still using the dummy url.

**Comment by Tokle89** [comment]
i have updated the getListOfListings function, to that it now uses the production/testing api, instead of the dummy url

**Comment by runeunhjem** [comment]
Closing this ticket for cleanup purposes and solutions have been implemented
Reopen if needed
