### ISSUE TITLE
h1 on the "Sign In" page has got a different font weight than the others

### ISSUE THREAD

**Issue by karolina-szymanska** [NoroffFEU/agency.noroff.dev#428]
The h1 element on the "Sign In" page has got a different font weight than the others.

Suggested solution: add the class .fw-bold responsible for adding the suitable font weight.

Sign In page:
<img width="563" alt="Screenshot 2023-10-31 at 14 08 28" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/79116755/36090f3b-68fd-4b02-956f-3be9a59343ec">

Register page:
<img width="845" alt="Screenshot 2023-10-31 at 14 08 56" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/79116755/49f6653d-f013-455e-a78b-8c8df16d183d">

**Comment by bonitadiener** [comment]
It is looking much better @karolina-szymanska
