### ISSUE TITLE
FE-application || View all application

### ISSUE THREAD

**Issue by Christonn93** [NoroffFEU/agency.noroff.dev#43]
Please note: This task requires additional design work before it can be completed.

**Comment by asimenstad** [comment]
@Christonn93  Which wireframe is this based on? Applications sent on student profile or applications received on company profile? Or on admin page?

**Comment by Christonn93** [comment]
I will check it and let oyu know @asimenstad

**Comment by Christonn93** [comment]
@asimenstad  I have not figured that out. It was clear on the first wireframe that we had but now its not so clear. Now it looks like its added onto the profile page

**Comment by runeunhjem** [comment]
Closing this ticket as it is outdated and no longer relevant
