### ISSUE TITLE
Update installing and starting the project in readme.md

### ISSUE THREAD

**Issue by jonnebonde** [NoroffFEU/agency.noroff.dev#447]
By following the instructions in the readme.md file im not getting the styling to work on the live-server or dev-server.
By running command "npm run build" everything worked on my side.

**Comment by Bjonne696** [comment]
Update works, and styling is shown when running the command npm run build

**Comment by Bjonne696** [comment]
merged branch with main branch

**Comment by jonnebonde** [comment]
Nice, thank you.
