### ISSUE TITLE
Duplicate use of the same ID

### ISSUE THREAD

**Issue by martindyr** [NoroffFEU/agency.noroff.dev#452]
In the page ``pages/admin/index.html`` the search forms in different tabs all have the same ID (usersSearchForm). IDs should be unique within a page.

- [ ] Change from ID to class

**Comment by Ninuskaninus** [comment]
Pull request 
https://github.com/NoroffFEU/agency.noroff.dev/pull/497

**Comment by AnaCascante** [comment]
@KevinHavn is this issue finished and merged? then it can be closed :)
