### ISSUE TITLE
Hide missing img if the user dont have Avatar yet

### ISSUE THREAD

**Issue by martindyr** [NoroffFEU/agency.noroff.dev#453]
How to recreate issue:
1. Create profile
2. Exclude profile image
3. login
4. Go to profile
Result: User sees the image below -> undeinfedavatar
- [ ] If the user dont have avatar, show default image or no image?

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/76110230/899b3a3a-fd81-4cad-abc7-cdb5833f4c57)

**Comment by mathiasg12** [comment]
are you working on this your self or is it free to take? I see you are assigned to this task but it isnt assigned to a team

**Comment by martindyr** [comment]
> are you working on this your self or is it free to take? I see you are assigned to this task but it isnt assigned to a team

Go for it!

**Comment by MHerholdt94** [comment]
Hello!

I believe this is being tackled in issue #515 , where a placeholder image is used if no avatar is found.

**Comment by mathiasg12** [comment]
yes, it was fixed in a earlier version

**Comment by runeunhjem** [comment]
I will close this ticket as it has been solved as mentioned above here
