### ISSUE TITLE
Search Icons using wrong src

### ISSUE THREAD

**Issue by martindyr** [NoroffFEU/agency.noroff.dev#454]
### Would like some input from the team on this

The image below shows that the src the ``Img`` is using is wrong.
The image is using ``/assets/icons/search.svg`` when it should be ``/public/assets/icons/search.svg``

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/76110230/94785dcf-fb4f-4f8f-b165-0c71fbcd5803)

**Comment by Kobraz** [comment]
I have fixed the source for search.svg on the three pages where these icons are.



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16524760/3fa132e1-8640-4f76-aeb4-ef7f6721a393)

**Comment by runeunhjem** [comment]
Pull request Search icons using wrong src - updated #488

**Comment by runeunhjem** [comment]
Awaiting to see if the vite configuration might be the sitewide reason that paths are not working.
Have reached out to Ana in Vettakollen

**Comment by Kobraz** [comment]
Made PR: [Made PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/488](Made PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/488)
