### ISSUE TITLE
Fix missing logo on landing page

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#456]
Change source of logo on landing page so it is showing

**Comment by runeunhjem** [comment]
Logo is missing in header - correct the src so it shows on all pages

**Comment by EkaterinaNattrass** [comment]
The logo is visible locally, but not globally. So probably the src has nothing to do with the problem. I have changed the html from img to embed, which is supposed to fix the issue, but can't be sure until it's pushed to the main branch and we can see the website page.

**Comment by runeunhjem** [comment]
Pull request: https://github.com/NoroffFEU/agency.noroff.dev/pull/471

**Comment by runeunhjem** [comment]
Awaiting to see if the vite configuration might be the sitewide reason that paths are not working.
Have reached out to Ana in Vettakollen

**Comment by EkaterinaNattrass** [comment]
Thank you, Rune. Also trying to figure it out myself. Keep me posted if you learn smth from Ana.

**Comment by EkaterinaNattrass** [comment]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114596712/6a68ed85-63ec-4ff3-a0ab-327c46a1a3a4)

According to Vite.js documentation, you are supposed to use absolute path. So theoretically the path is right. But Ole is right as well,  the image does appear if you add public/....
According to the doc, you can also use import with static assets. Trying it now
