### ISSUE TITLE
Register form success message responsive

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#461]
- Make success message responsive. Right now, the "login" link is in a green color, and the background is also green, and difficult to see. 
- Remove green color from link and have it underlined, and/or in capital/bold letters. Link should have correct contrast ratio, use contrast checker when adding color. 

Image:
<img width="515" alt="Screenshot 2024-01-08 at 11 51 32" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/282562ef-46b3-4715-9172-1f67d8a4a23d">

**Comment by EM-90** [comment]
Hey! I can see that the message is responsive now, there was probably someone else working on it. But i will change the color to get it WCAG compliant as mentioned in the task description.

**Comment by kribac12** [comment]
Great, @EM-90 , do that. I will talk to the other scrum masters about assigning tasks.

**Comment by Psijii** [comment]
This needs to be entirely re-created and a new branch, too many conflicts in the package to resolve it.

**Comment by kribac12** [comment]
@EM-90 Can you fix this? It is not responsive as of now because of conflicts.

**Comment by EM-90** [comment]
I am not sure i understand? i only changed the $primary variable so that the color on the link and active colors on the boxes changed to blue, and it worked perfectly when i was finished. Can you tell me a bit more about the conflict, so i can avoid doing the same thing over again @Psijii ?

**Comment by AndreasYager** [comment]
@EM-90 I just finished working on task #558, where I saw you commented about changing the primary color. When I tried to change $primary in the theme colors I noticed it made a significant amount of changes to the src/scss/index.css file. I instead found the specific CSS rule responsible for the box-shadow primary color in the src/scss/index.css file and updated just that one. 

Not sure if that is part of the conflict here? Perhaps there is a more specific styling that should be changed instead?

**Comment by EM-90** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/684

@Psijii

**Comment by kimrm** [comment]
Reviewed and approved.

**Comment by kimrm** [comment]
I'm moving this to done. Just a heads up that deployment is currently failing because of a change someone has done in the Vite build config. This task will eventually be closed when the merge and deployment run successfully.

**Comment by AnaCascante** [comment]
@kimrm is this issue finished and merged? then it can be closed :)
