### ISSUE TITLE
sort function not responsive, 2 sort icons.

### ISSUE THREAD

**Issue by nyolarraklay** [NoroffFEU/agency.noroff.dev#462]
When you click the sort icon, the dropdown shows the label but the sort function is not working

**Comment by nyolarraklay** [comment]
The API is not related to Job listings, the API is a list of products and everything else. it is not possible to sort it by the date posted.
- fetch the API
- change the lists in the dropdown element of sort icons
- create a sort functions

**Comment by nyolarraklay** [comment]
PR for review
https://github.com/NoroffFEU/agency.noroff.dev/pull/481

**Comment by nyolarraklay** [comment]
the function is using a dummy API. will try to use the actual url

**Comment by Sovak3441** [comment]
Please resolve the merge conflicts.

**Comment by nyolarraklay** [comment]
i think it was resolved by another team. i will just close this one. i will make a new issue about the API in listing page

**Comment by nyolarraklay** [comment]
i think it was resolved by another team. i will just close this one. i will make a new issue about the API in listing page
