### ISSUE TITLE
Create Pull Request template

### ISSUE THREAD

**Issue by kyrregjerstad** [NoroffFEU/agency.noroff.dev#464]
# Create Pull Request template

## Description
Currently, the repository lacks a Pull Request template. This absence often leads to PRs that vary significantly in structure and content, making them challenging to review efficiently and effectively. To streamline the PR review process and maintain consistency, we could introduce a standard PR template.

## Expected Outcome
- Creation of a PR template in Markdown format.
- The template could include sections like **Title**, **Description**, **Type of Change**, **Checklist**, **Screenshots** (if applicable), **Test Plan**, **Related Issue** (linking to the issue that the PR addresses), and **Additional Information**.
- The template should be straightforward, guiding student to provide all necessary information without being overly verbose.
- The template should reside in a `.github/PULL_REQUEST_TEMPLATE.md` file at the root of the repository.

## Additional Information
The implementation of this PR template aims to improve the project's workflow, making it more contributor-friendly and maintainable. A well-defined template will ensure that all PRs meet a minimum standard of information, thus aiding students, reviewers and QAs in their tasks.

## Helpful References
- [GitHub documentation on PR templates](https://docs.github.com/en/articles/creating-a-pull-request-template-for-your-repository)
- [GitHub About issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

*Please feel free to suggest any additional sections or modifications to the proposed template that might be beneficial for the project.*

**Comment by Kobraz** [comment]
Made pull request #590

[https://github.com/NoroffFEU/agency.noroff.dev/pull/590](https://github.com/NoroffFEU/agency.noroff.dev/pull/590)


This is the Pull Request Template:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16524760/08dc0fb7-435e-45f6-b1f9-e5b4ee7fe975)

Tested the Pull Request Template while doing PR on this one:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16524760/ad4375cf-d49f-4be0-a8da-7c1575129c39)

**Comment by runeunhjem** [comment]
Pull request: https://github.com/NoroffFEU/agency.noroff.dev/pull/590

**Comment by Kobraz** [comment]
New PR [#590](https://github.com/NoroffFEU/agency.noroff.dev/pull/590)

**Comment by runeunhjem** [comment]
Approved by QA's and Kyrre, so ready for use as PR Template
