### ISSUE TITLE
Close icon on add image doesn't match figma

### ISSUE THREAD

**Issue by ESPR07** [NoroffFEU/agency.noroff.dev#465]
Icon seems to be missing due to faulty path.

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111272036/213c54af-abb2-40a6-a231-094935a1f14d)

**Comment by bLangved** [comment]
Problem was allready fixed, though I can't find the issue for it, or if somebody has documented anything.
Closing issue
