### ISSUE TITLE
Consistency for registration inputs, rounded corners

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#467]
- Make all inputs have rounded corners.
- As for now, Email and Degree(s) inputs are the only ones to not have rounded corners. 

Image:

<img width="678" alt="Screenshot 2024-01-08 at 12 27 21" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/9f7a7672-1e97-4050-9fc1-41cd80016d16">

**Comment by kribac12** [comment]
Great, @mhaarseth, wise to get to know the project before taking on both smaller and bigger tasks. Let me know if you encounter obstacles and how you get on with the task.

**Comment by kribac12** [comment]
@mhaarseth You can do what makes the most sense to you.

**Comment by mhaarseth** [comment]
I'll do it as part of this then. Seeing as it's so tightly connected to the "Register For Applicant" form, and the issue name doesn't state it only concerns the applicants form. Thank you for weighting in :)

**Comment by kribac12** [comment]
@mhaarseth how are you getting on with this task? If you need input from the other devs, you can tag them here.

**Comment by mhaarseth** [comment]
Yes, of course, sorry! 
Pr: https://github.com/NoroffFEU/agency.noroff.dev/pull/563

**Comment by Psijii** [comment]
Commented on the PR
