### ISSUE TITLE
Listings - Horizontal Scroll

### ISSUE THREAD

**Issue by Queenen** [NoroffFEU/agency.noroff.dev#468]
<img src="https://i.imgur.com/CmyIIie.png">

pages/listings/index.html

There's a horizontal scrollbar that needs to be resolved. This occurs at all widths.

**Comment by hah98** [comment]
It seems like the horizontal scrollbar has been resolved, there is no horizontal scrollbar when I check, What is the status on this issue now @Queenen ? Have you resolved it? if not, let me know!

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/905bdeff-0839-4e68-9cb5-494096705f04)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/d8c41632-7906-40c2-ba93-60afbc311df4)

**Comment by Queenen** [comment]
> It seems like the horizontal scrollbar has been resolved, there is no horizontal scrollbar when I check, What is the status on this issue now @Queenen ? Have you resolved it? if not, let me know!
> 
> ![Image](https://private-user-images.githubusercontent.com/74331454/295379858-905bdeff-0839-4e68-9cb5-494096705f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzg4MzQsIm5iZiI6MTcwNDg3ODUzNCwicGF0aCI6Ii83NDMzMTQ1NC8yOTUzNzk4NTgtOTA1YmRlZmYtMDgzOS00ZTY4LTljYjUtNDk0MDk2NzA1ZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA5MjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMGU0YzNjMjVkMmVkNGViZTU1NGE4ZmI3ODM3ZWU4MzRkMTUxMmZhM2Y1ZmM2MmI5ZjI2ZjFmMmJhN2UzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlSSi_Ch-Rehxowt0NYO2_aTr5qwe5x9LJgNdXOe4r8) ![Image](https://private-user-images.githubusercontent.com/74331454/295379857-d8c41632-7906-40c2-ba93-60afbc311df4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzg4MzQsIm5iZiI6MTcwNDg3ODUzNCwicGF0aCI6Ii83NDMzMTQ1NC8yOTUzNzk4NTctZDhjNDE2MzItNzkwNi00MGMyLWJhOTMtNjBhZmJjMzExZGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA5MjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNDExZmQwOGFkMDE5NWE0MjAxNGYwZTBkNTU3NmZkOTEzM2Q1ZTMyODdkMTA4NGE2MTYwZjkzMDkxMzFhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bS3Bv1PTjWcB4wOXHa0_5Qa6q-UPytjxl3TNzpL71bI)

Yes, this issue seems to have been resolved by someone.

**Comment by AnaCascante** [comment]
@Queenen  is this issue finished and merged? then it can be closed :)

**Comment by Queenen** [comment]
> @Queenen is this issue finished and merged? then it can be closed :)

Yes, I'm closing this issue.
