### ISSUE TITLE
Fix profile page authentication

### ISSUE THREAD

**Issue by AnaCascante** [NoroffFEU/agency.noroff.dev#470]
- [x] Redirect user to login/registration page if they attempt to access profile page with URL (i.e. "agency.noroff.dev/pages/user/index.html")
- [x] Make sure link to profile page only shows up when user is logged in (don't forget the hamburger menu!)

**Comment by Sovak3441** [comment]
Profile page can not be accessed while not logged in. Trying to access through URL redirects back to index.
