### ISSUE TITLE
Listings - Content gets cropped at lg breakpoint

### ISSUE THREAD

**Issue by Queenen** [NoroffFEU/agency.noroff.dev#472]
<img src="https://i.imgur.com/lcLE4UA.png">

pages/listings/index.html

The content is not responsive at large break point (992px) which causes horizontal scrolling.

**Comment by RamtinMoshtagh** [comment]
@Queenen What is the status here? I can work in this issue. please update me :)

**Comment by Queenen** [comment]
> @Queenen What is the status here? I can work in this issue. please update me :)

I have not yet started working on this, but the content is removed however. 
So I'm guessing that if not you, someone else is currently working on the issue.

**Comment by RamtinMoshtagh** [comment]
Thanks for clarifying. Yes, im sure someone is working on it.

**Comment by runeunhjem** [comment]
Closing this as it is not assigned, and Sprint 2 will get Team Holmenkollen on listings issues
