### ISSUE TITLE
The Privacy page has two 'back' buttons

### ISSUE THREAD

**Issue by EkaterinaNattrass** [NoroffFEU/agency.noroff.dev#473]
There are two 'back' buttons: one on top and one at the bottom, which is probably not the best UX experience. 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114596712/f4d2d439-1f88-45cd-bf44-0101d05c45f0)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114596712/fa56facd-a170-4cf9-81f1-ada0bb22efa5)

**Comment by chrisbekk** [comment]
Do we have any design docs that indicate which button that should be removed? I´m leaning towards removing the top button, but can anyone from design chip in on this?

**Comment by KarenJoo** [comment]
Have you checked out the agency figma files: https://www.figma.com/files/project/78324144/agency.noroff.dev?fuid=1141686962066314065 ?

**Comment by Christelmarita** [comment]
@chrisbekk which button did you delete?
I´m currently working on the same issue on the Terms of Use page.

**Comment by KarenJoo** [comment]
Hey Christelmarita, you will get an answer on this asap. Dev and QA will clarify with you before any merge.

**Comment by chrisbekk** [comment]
@Christelmarita I deleted the top button on the policy page.

**Comment by AnaCascante** [comment]
@Jean-Christoffer is this issue finished and merged? then it can be closed :)
