### ISSUE TITLE
Change text color of buttons to match Figma design

### ISSUE THREAD

**Issue by eskiltorset** [NoroffFEU/agency.noroff.dev#475]
The buttons on the webpage has black color while the Figma file has white.

Webpage:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/44784426/cec35a0e-2f7d-4dfa-b051-f88e89a6e333)

Figma design:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/44784426/f8334ae1-f020-4993-8da7-ff29de3cdd80)

To do: Make all colors to match the colors of the Figma design.

**Comment by KarenJoo** [comment]
Link to Agency figma file: https://www.figma.com/files/project/78324144/agency.noroff.dev?fuid=1141686962066314065
