### ISSUE TITLE
"Add image" button on register form differs from prototype

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#476]
- "Add image" link background is too small and differs from the prototype.
- Looks out of place, should adhere to the prototype version if not taking on the same design as the other input fields. 

Images: 

<img width="295" alt="Screenshot 2024-01-08 at 13 54 55" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/b6431a30-6da3-4343-8955-40ce162780bd">
<img width="605" alt="Screenshot 2024-01-08 at 13 55 09" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/cd64c464-49c7-417d-bcad-aa1729f97f8d">

**Comment by kimrm** [comment]
A solution for this could be to add padding on the button. This will make the button fill the circle DIV that wraps it, and make the whole thing clickable. I'm testing this now and will create a PR if this works well.

**Comment by kimrm** [comment]
PR: 510

https://github.com/NoroffFEU/agency.noroff.dev/pull/510

**Comment by Psijii** [comment]
Reviewed and accepted. 
Looks good!

**Comment by kimrm** [comment]
@Psijii 

Created a new PR https://github.com/NoroffFEU/agency.noroff.dev/pull/546 too fix the earlier overwriting incident.

**Comment by kimrm** [comment]
The PR for this issue seems to have been overwritten by some other PR.

**Comment by kimrm** [comment]
@Psijii 

New PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/579

**Comment by kimrm** [comment]
Fixing this in issue 661.
