### ISSUE TITLE
Register form: switch between applicant/company more visible and center heading

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#478]
- Not easy to spot the "Not an applicant? Register as a company instead!"-link, might make user start filling out the form before spotting it, even if heading says it's for applicants.
- Future solution if time, use nav pills between applicant and company, have applicant as default when clicking on "register" link. 
- For now, make "Not an applicant.."-link more visible by moving it further up, beneath heading, so companies do not have to look further. 

<img width="679" alt="Screenshot 2024-01-08 at 14 06 01" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/4fe8e506-3ac8-4adf-8201-b5dc3254b7d6">

**Comment by LineNil** [comment]
Pull request: #538

**Comment by LineNil** [comment]
This pr is only for Applicant

**Comment by Psijii** [comment]
Commented in PR
