### ISSUE TITLE
Fix email still being stored in local storage if "remember me" is unchecked

### ISSUE THREAD

**Issue by MHerholdt94** [NoroffFEU/agency.noroff.dev#487]
# Issue
Email address is stored in local storage if user logs in with "Remember me" unchecked.

## Fix
_login()_ function in _api/auth/login.js_ needs to be slightly modified to make sure email address is properly stored depending on "Remember me" checkbox state when logging in.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/81162745/6139e98f-76c3-4842-b877-99d2a0c7d4cb)

## Outcome
Expected outcome of this is the email address being stored in session storage if "Remember me" is unchecked during login.

**Comment by Ninuskaninus** [comment]
pull request #496

**Comment by AnaCascante** [comment]
@KevinHavn is this issue merged? then it can be closed ;)
