### ISSUE TITLE
Broken image in navbar

### ISSUE THREAD

**Issue by Noroff-Anders** [NoroffFEU/agency.noroff.dev#491]
Broken image in navbar

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/98edbadf-edeb-4f17-abde-e6bf78423c57)

![bilde](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/635de052-62cc-40c2-81cb-c1a2b7dd4ada)

**Comment by thikimyen-nguyen** [comment]
I found also missing alt for this image.

**Comment by runeunhjem** [comment]
Duplicate of ticket #456

**Comment by Noroff-Anders** [comment]
oki, closing this :)
