### ISSUE TITLE
Listin page - missing icons and duplicate sort button

### ISSUE THREAD

**Issue by Noroff-Anders** [NoroffFEU/agency.noroff.dev#501]
Need to check this on the listing page. Works fine locally trough live server for som reason

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/82e8dacb-525e-4ce5-8421-d0616d4d4cd0)

**Comment by ESPR07** [comment]
little heads up that #462 is already working on this I believe.

**Comment by Noroff-Anders** [comment]
oki thanks for the heads up. Closing this then :)
