### ISSUE TITLE
Register form border radius

### ISSUE THREAD

**Issue by Noroff-Anders** [NoroffFEU/agency.noroff.dev#502]
Register form inputs has different border radius on the inputs

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/27a4acae-7c5a-429e-8542-401da7690ec9)

**Comment by kribac12** [comment]
We in Korketrekkeren worked on this yesterday morning, and added the issue earlier, so I have added "Duplicate" as a label. Please check that the issue does not already exist before adding it.

**Comment by Noroff-Anders** [comment]
Oki, closing this :)
