### ISSUE TITLE
Register form - Wording spacing

### ISSUE THREAD

**Issue by thikimyen-nguyen** [NoroffFEU/agency.noroff.dev#505]
There is a little spacing error for wording under Register button. Consider to make it more readable and consistent to Login form.
![Screenshot 2024-01-08 at 22 13 29](https://github.com/NoroffFEU/agency.noroff.dev/assets/114567641/b9b720e6-bf68-4149-bd12-af25b08dfbad)
![Screenshot 2024-01-08 at 22 16 40](https://github.com/NoroffFEU/agency.noroff.dev/assets/114567641/83e71b5c-2e90-4c9b-9052-4d04b7695c67)

**Comment by thikimyen-nguyen** [comment]
Need to check both register forms for applicants and companies.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114567641/252aca1f-89b5-47b6-bc5e-50d21f752d14)

**Comment by AnaCascante** [comment]
@Sugal99 is this issue QA and merged? then you can close the issue ;)
