### ISSUE TITLE
Home Page - View Listings button navigates to login page

### ISSUE THREAD

**Issue by thikimyen-nguyen** [NoroffFEU/agency.noroff.dev#506]
When click on the button View Listings on home page, it navigates to Log in page.

**Comment by Tokle89** [comment]
Is the issued with the listing button linking to the loggin page resolved? 
I have tried to login in, and then press the listing button on the home page, and it still takes me to the login page

**Comment by maleneivy** [comment]
Got merged with wrong code by mistake, new PR here: https://github.com/NoroffFEU/agency.noroff.dev/pull/550

**Comment by AdrianMikk** [comment]
I did something wrong while fixing the conflict, it was working. I'm doing it again now. Working soon @Tokle89
