### ISSUE TITLE
No Log Out button shown after log in successfully

### ISSUE THREAD

**Issue by thikimyen-nguyen** [NoroffFEU/agency.noroff.dev#509]
There should be Log Out button instead if user logged in.
![Screenshot 2024-01-08 at 23 02 06](https://github.com/NoroffFEU/agency.noroff.dev/assets/114567641/1bfb2046-1930-4549-9744-045966a8d6fd)

**Comment by kyrregjerstad** [comment]
I think this is already solved in https://github.com/NoroffFEU/agency.noroff.dev/pull/489

**Comment by MHerholdt94** [comment]
kyrregjerstad is correct! :) although the button doesn't do anything yet

**Comment by AnaCascante** [comment]
@Miksel90  issue closed ;)
