### ISSUE TITLE
FE-application || User can apply to a lisitng

### ISSUE THREAD

**Issue by Christonn93** [NoroffFEU/agency.noroff.dev#51]

**Comment by AugustWahlberg** [comment]
@Christonn93 To ensure that I understand the task correctly:

In this task should I create the JS code to handle the input in the form on the site called "Cover Field Letter"? I find the HTML markup for this page in the main branch under pages/admin/application/apply/index.html

**Comment by Christonn93** [comment]
@AugustWahlberg 

You need to make a function that allowed the user to apply on a job listing. 
not sure according to the wireframe witch this is atm. 

Here is where i would say that it is in this area of the [flow](https://www.figma.com/file/Zmjgin8hKs28pgxdJDwmcc/Information-Architecture?node-id=0%3A1&t=HlY1xqGCbsOtxEEM-0):
![image](https://user-images.githubusercontent.com/46559129/213373964-311d9998-9963-46d1-8b51-d0dfe8d528e3.png)

When a user see a job application, that they wan't to applay on, we need the function for making the call to the api, and receive a feedback to the user if everything is ok.

**Comment by runeunhjem** [comment]
Outdated - Make new ticket if issue still applies
