### ISSUE TITLE
Hamburger-button has no animation

### ISSUE THREAD

**Issue by YngvN** [NoroffFEU/agency.noroff.dev#513]
The button doesnt have an animation when clicked, and also doesnt become an X. 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/107488803/3ec8fa1e-10a3-4353-a511-e2e3632215fb)

**Comment by bLangved** [comment]
Was this fixed, @YngvN ?
If not, I am working on a larger issue https://github.com/NoroffFEU/agency.noroff.dev/issues/672 I will add this as a subtask

**Comment by YngvN** [comment]
@bLangved This is fixed and it also solved the alignment of the hamburger as a bonus
