### ISSUE TITLE
Profile || Hardcoded user details

### ISSUE THREAD

**Issue by MHerholdt94** [NoroffFEU/agency.noroff.dev#515]
# Issue
User details like name, skills etc. are hardcoded in the HTML for the profile page. This makes it so the hardcoded details appear before it is replaced with the fetched user details from the API.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/81162745/69d9fe9e-792b-4279-a590-8fddd50fabec)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/81162745/14b8b8d7-d1f0-445c-a9fd-b09cd85e1cb3)

## Fix
Remove hardcoded details from the HTML and add a dynamic solution for displaying user details.

## Outcome
Opening profile page should neatly and quickly display the correct user details

## Other ideas
- Add a placeholder profile picture if no avatar is found
- Add placeholder text if "skills" or "about me" is empty/not found

**Comment by Chrissebah** [comment]
Removed the hardcoded details from the html and added some simple js to userDetailsTemplate.js to add a placeholder for the image if the user does not have one.

**Comment by Sovak3441** [comment]
No pull request linked.. Hence no way to test any code relating to this.

**Comment by Chrissebah** [comment]
Sorry. I believe it is this if I am not mistaken: https://github.com/NoroffFEU/agency.noroff.dev/tree/%23515-Profile---Hard-Coded-User-Details

**Comment by Chrissebah** [comment]
I made some changes. Hoping that fixes it. If not then I am unsure as to what I have to do to fix it.

**Comment by Sovak3441** [comment]
Closed as part of Sprint 2. There is still MC to resolve, and it does not pass deploy testing
