### ISSUE TITLE
Missing email validation for login form

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#518]
There is no immediate email validation for the login form, most likely due to the input not having email attribute.
- Check to see what is wrong and try to find a solution. 

<img width="453" alt="Screenshot 2024-01-09 at 10 10 04" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/4426c731-54c0-4092-b0e3-52ca3a65a2e8">

**Comment by kimrm** [comment]
Adding input type="email" fixes the validation, and also prevents the "unknown error" message if the user inputs something other than a email address.
I will make the change and create a pull request shortly.

**Comment by kimrm** [comment]
@Psijii 

Pull request: https://github.com/NoroffFEU/agency.noroff.dev/pull/542

Changes made: adds input type="email" to email input field.

**Comment by kimrm** [comment]
The PR for this issue seems to have been overwritten by some other PR.

**Comment by kimrm** [comment]
@Psijii 

New PR:  https://github.com/NoroffFEU/agency.noroff.dev/pull/580

**Comment by Psijii** [comment]
Commented on PR 580
