### ISSUE TITLE
Register form immediate validation

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#519]
- Validation is only shown after clicking on "Register" button, after the user has filled in all or none of the inputs. 
- Validation should show immediately after moving on to the next input, to make user experience better. 

<img width="874" alt="Screenshot 2024-01-09 at 10 16 41" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/06005334-ca03-4fef-9a2a-88122c521759">

**Comment by ellie489** [comment]
Changed innterHTML to "Incorrect E-mail/password". However, I got this error: 2:10  error  'apiPath' is defined but never used  no-unused-vars, so I also removed the unused import.

**Comment by ellie489** [comment]
1. Makes functions to validate inputs immediately.
2. Refactors validation functions to make them more modular.
3. Creates new file "validateInputs.js", then exports the functions.
4. Imports functions in "setRegisterFormListenerApplicant.js".
5. Updates code to use the new imported functions. 
** When testing the functions on live server, I found another issue. The error messages appearing under the inputs are just regular text, when they should communicate an error, for example by using colors.

**Comment by ellie489** [comment]
PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/632 @Psijii ready for QA.

**Comment by kimrm** [comment]
@ellie489 I'm testing this PR now. The validation works perfectly as far as I can tell. Good work!
However, there's an error when clicking the submit button that prevents the form from being submitted. I haven't dug into the problem yet so I don't know exactly what the issue is. I can have a look by tomorrow and see if I can resolve it.

@Psijii

**Comment by kimrm** [comment]
Sorry, I was not able to answer before now.

File: /src/js/listeners/auth/setRegisterFormListenerApplicant.js

This specific error is related to the variable fullName being treated as an array in the form submit event listener.
These two lines nr 44 and 45:
`
profile.firstName = fullName[0];      
profile.lastName = fullName.slice(1).join(' ');
`

In line 9 the fullName variable is set, but it is set to the element with ID fullName, not an array. So the code is trying to treat the HTML element as an array.
Line 9: `const fullName = document.querySelector('#fullName');`

In the submit event listener there should be som logic to split the value from the fullName input element into an array and set this to a new variable. Then change to something like this:
`
profile.firstName = newVariableName[0];      
profile.lastName = newVariableName(1).join(' ');
`

**Comment by kimrm** [comment]
> Great, Thanks! Looks like I removed the `const form = event.target` on line 16. I dont think I was supposed to do that, can You check If Thats the reason?

I don't think it's a problem that you removed it. The submit event is triggered and the form data is coming through.
