### ISSUE TITLE
login function has a wrong APIpath

### ISSUE THREAD

**Issue by nyolarraklay** [NoroffFEU/agency.noroff.dev#520]
errors show when the user logs in. it says the "URL is not found"

**Comment by nyolarraklay** [comment]
done
https://github.com/NoroffFEU/agency.noroff.dev/pull/533

**Comment by Sovak3441** [comment]
Please resolve Merge Conflicts in Index.html, getListOfListings.js and renderListings.js

**Comment by nyolarraklay** [comment]
done
