### ISSUE TITLE
Login button - Fix linebreak

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#524]
Make it so it does not show on two lines on smaller screen sizes

**Comment by Kobraz** [comment]
Done these changes in src/scss/custom/_headers.css:

#navUI --> Added white-space: nowrap;


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16524760/f1553197-7ba2-4dd2-9414-0ba325c1afaa)

**Comment by runeunhjem** [comment]
Pull request: https://github.com/NoroffFEU/agency.noroff.dev/pull/529

**Comment by Kobraz** [comment]
Pull request [#529](https://github.com/NoroffFEU/agency.noroff.dev/pull/529)

Removed the changes from #454 that was not supposed to be included in this.
