### ISSUE TITLE
Login form: Incorrect username/password should show E-mail instead of username

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#534]
- correct error message to say "Incorrect E-mail/password" instead of "Incorrect username/password"

<img width="162" alt="Screenshot 2024-01-09 at 11 43 07" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/ce4acdf9-c5c5-4f5d-9262-3492259af328">

**Comment by ellie489** [comment]
Link to PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/592 @Psijii please QA this PR, thank you.

**Comment by kimrm** [comment]
PR #592 approved and merged.
