### ISSUE TITLE
Error-handling || Replace console logs

### ISSUE THREAD

**Issue by MHerholdt94** [NoroffFEU/agency.noroff.dev#536]
# Issue
The error-handling is almost exclusively console logs that either logs the string "Error" or the catched error in try/catch blocks

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/81162745/79ef1884-c16f-4668-aed5-ed32a0e462d3)

## Fix
Replace console logs with proper error-handling to ensure robustness and usability across the application.

## Other ideas
- Ensure relevant and user-friendly error messages are displayed to the user upon encountering an error. 
- Create a reusable "displayMessage" function.
- Add fallback strategies. For example use cached data in case of network request error.

**Comment by MHerholdt94** [comment]
**Update 11.01.2024**
This issue is cut down to only include a few files in an effort to reduce potential merge conflicts

**Comment by MHerholdt94** [comment]
PR #693

**Comment by Sovak3441** [comment]
Merged
