### ISSUE TITLE
Validation method in register form differs for different browsers

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#551]
- The current validation is not sufficient across browsers, ie the safari browser only tells the user to use the correct format without description. 
- Should add a custom error message to the user and prevent browser default.

**Comment by ellie489** [comment]
After working on issue 519 (Immediate form validation) there are error messages appearing using JS under each input. However, they are just regular text, so we need to implement some color, icon, box etc for the error messages.

**Comment by kimrm** [comment]
This task should probably be closed or renamed to something related to styling of the validation messages, given that the validation issue will be solved by issue 519.

**Comment by kribac12** [comment]
@ellie489 @kimrm is validation working across different browsers now?

**Comment by ellie489** [comment]
Yes, I have now removed the browser default handling. As Kim said we still need styling, but the functionality is implemented. @Psijii ready for QA: [PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/781 )

**Comment by kimrm** [comment]
Reviewing

**Comment by kimrm** [comment]
Approved
