### ISSUE TITLE
Navbar not changing to have logout button after login

### ISSUE THREAD

**Issue by ESPR07** [NoroffFEU/agency.noroff.dev#552]
It doesn't seems to be able to tell that I'm already logged in, so I get no logout Button.

![bilde](https://github.com/NoroffFEU/agency.noroff.dev/assets/111272036/596fad74-f4f6-42a6-873c-8c438c8c2beb)

I couldn't quite figure out why it's not working or how it verifies, but I also get two different "role" in local storage on login. both a "Role" where I get "null" and a "role" where I get "Applicant".

**Comment by Jarle302** [comment]
Are you able to reproduce the bug? :)

**Comment by ESPR07** [comment]
Happens every time I log in with my created account

**Comment by ESPR07** [comment]
Okey so now I get in, but it doesn't reflect on the profile page, everything on profile is just placeholders now

**Comment by nyolarraklay** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/670

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114483893/6e9288fa-af72-41e1-b77c-db958382c400)
