### ISSUE TITLE
Inputs on register form has green borders when active, indicating success even with no input or wrong input

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#558]
- The inputs on register form have green borders. Suggestions:
- should either become green if the input is correctly validated, 
- or even simpler, not become green at all but show the active state another way without the green colour (style with shadow or something else).

<img width="377" alt="Screenshot 2024-01-09 at 14 23 30" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/5844a109-1e4a-40ec-972d-05b693279f02">

**Comment by kribac12** [comment]
Waiting for developer to get added to group, will then assign task to them.

**Comment by EM-90** [comment]
Hey! quick update here. When i Changed color of the link on the success message register, i Changed the color of the $Primary variable, this variable is also used on the input when active. So the input should be blue when active instead of green?

**Comment by kimrm** [comment]
@EM-90 

The $primary variable is currently green in the main branch. I believe the PR where you changed this didn't get merged. Check with @Psijii

**Comment by kribac12** [comment]
@EM-90 It seems these changes are not in effect, please check if the PR is merged. If it is, and nothing happened, I believe you should add a new branch to fix both issues regarding the active colour. You might want to be more specific with the styling for both borders and the link in the success message so it is not as vulnerable to changes for primary colour.

**Comment by AndreasYager** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/666

In this version the form field box-shadow should be grey, updated from green. @kribac12 @Psijii

**Comment by kimrm** [comment]
I'm reviewing this now.

**Comment by kimrm** [comment]
@AndreasYager I have posted a comment on the PR.

**Comment by kribac12** [comment]
@kimrm should this be moved to "Doing"?

**Comment by kimrm** [comment]
@kribac12 I have requested some changes, so yes. I'll move it.

**Comment by EM-90** [comment]
Should this task be moved to done? Since the borders are blue due to the change in the $primary variable on the success-message task. @AndreasYager  . I am trying to see if there are many places this color change, But right now i have a problem with the css, maybe because of the Vite build that was mentined on teams earlier

**Comment by kimrm** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/666 approved.

**Comment by AnaCascante** [comment]
@kimrm Hi, if this task is done, QA and aproved you can close it ;)
