### ISSUE TITLE
Change form sent when register company

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#560]
register-company.js:24         
POST https://cors.noroff.dev/https://agency-api.noroff.dev/company 401 (Unauthorized)
registerCompany @ register-company.js:24
(anonymous) @ setRegisterFormListenerCompany.js:19
register-company.js:41 Error: 401 
at registerCompany (register-company.js:38:15)
at async HTMLFormElement.<anonymous> (setRegisterFormListenerCompany.js:19:9)

**Comment by runeunhjem** [comment]
Awaiting clarification from Abi as to how to fix company need to be authorized to register

**Comment by elli95** [comment]
To clarify a bit about the current situation.
On the company registration page, it has been set up that we need a company name, email, password, contact person and telephone number to register a company.
But in the [api documentation](https://agency-api.noroff.dev/api-docs/#/Company/post_company), only name, sector, phone, logo and admin are avalable values.
Hence the need for clarification from Abi.

**Comment by runeunhjem** [comment]
Postman gives this response:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/416e1339-cebf-4551-beaf-94f626096c28)

**Comment by elli95** [comment]
Updated form input for company registration.
Removed the password field, added name value to the inputs and changed label text email to Sector.
401 error (No authorization header provided.) is still there, but now the form should have all the needed values to register a company based on the Api documentation.

**Comment by elli95** [comment]
New update, error is now 401 "Only clients can create listings."
Now Post request should hopfully work, if user is a client.
I do not have a client user to test this with.

**Comment by elli95** [comment]
Pull request [#700](https://github.com/NoroffFEU/agency.noroff.dev/pull/700)

**Comment by Olekrr** [comment]
Due to the lack of a client account, the information sent by the form has been tested in a mock server and appears to arrive correctly after @elli95 update. 
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/93515165/30683220-7d26-4c95-936b-f8724783d425)
