### ISSUE TITLE
Remove the email field from the edit profile

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#564]
Either remove email completely or just from what is being sent tot give email already exists error, 
or deactivate it and just have it as a placeholder showing current emailadress without the opportunity to edit it.
But it should not be sent to api

**Comment by elli95** [comment]
Removed the email input in the edit profile forum.

**Comment by elli95** [comment]
Pull Request [#566 ](https://github.com/NoroffFEU/agency.noroff.dev/pull/566)
