### ISSUE TITLE
Header mobile || Smaller screen size for dropdown

### ISSUE THREAD

**Issue by YngvN** [NoroffFEU/agency.noroff.dev#565]
The dropdown menu activates at 990px and I think it's bcause of bootstrap. It should be 768px to activate

**Comment by thikimyen-nguyen** [comment]
Someone in other team have logged the same issue ticket #627 
Should  either Mikeal or we tell them? @Miksel90

**Comment by bLangved** [comment]
Was this fixed, @YngvN ? 
If not, I am working on a larger issue #672 I will add this as a subtask
