### ISSUE TITLE
HomePage || NewListingsButton again redirects wrong after PR #555

### ISSUE THREAD

**Issue by maleneivy** [NoroffFEU/agency.noroff.dev#570]
Made changes to the button that worked and got overwritten again by pull request #555.

**Comment by KarenJoo** [comment]
Hi, please rename the branch removing the pipelines ( || ) as it is causing "error: cannot lock ref 'refs/remotes/origin/570-homepage-||-newlistingsbutton-again-redirects-wrong-after-pr-555': Unable to create". We did the same on another branch :)
