### ISSUE TITLE
Icons and logos are not in the correct path 

### ISSUE THREAD

**Issue by nyolarraklay** [NoroffFEU/agency.noroff.dev#585]
Icons in the footer section doesn't show 
Noroff Logos doesn't show

**Comment by nyolarraklay** [comment]
PR link
https://github.com/NoroffFEU/agency.noroff.dev/pull/586

**Comment by Sovak3441** [comment]
Please resolve merge conflict in login.js and editStudent.js.


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16456088/1401493f-d8a5-4d23-adbb-c7ec331fc717)



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16456088/53248ba8-b934-4cf2-9095-8259b7fb6ea9)
