### ISSUE TITLE
apiUrl is using wrong url

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#591]
export const apiUrl = new URL('https://cors.noroff.dev/https://agency-api.noroff.dev/listings/');

Should be 
export const apiUrl = new URL('https://cors.noroff.dev/https://agency-api.noroff.dev/');

Then make variables for the endpoints.

export const applicationUrl = "application/";
export const companyUrl = "comapny/";
export const listingsUrl = "listings/";
export const usersUrl = "users/";
export const offerUrl = "offer/";

And lastly change any url's in files that need changes to use these variables.

**Comment by RamtinMoshtagh** [comment]
@runeunhjem , ive assigned myself to this! Cool?
