### ISSUE TITLE
Home page for applicants: Content does not change after login

### ISSUE THREAD

**Issue by maleneivy** [NoroffFEU/agency.noroff.dev#593]

**Comment by Noroff-Anders** [comment]
Can u describe / take screenshot of what content is not changing after login?

**Comment by maleneivy** [comment]
![Skjermbilde 2024-01-10 kl  18 57 03](https://github.com/NoroffFEU/agency.noroff.dev/assets/68667843/4348ca16-6a6a-47f4-99da-a986ff019195)
This is the home page for when no one is logged in, but it is also the home page when an applicant is logged in. 

The design should be this: 
<img width="757" alt="Skjermbilde 2024-01-10 kl  18 58 29" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/68667843/a81b8afb-6920-490e-84d6-b210dc817c79">
