### ISSUE TITLE
Broken search icon on listing page

### ISSUE THREAD

**Issue by vanya992** [NoroffFEU/agency.noroff.dev#605]
Search icon on the listing page is broken

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/18acccbc-2a09-419d-a09b-71e1dc7009a2)

**Comment by Queenen** [comment]
I'll start working on it!

**Comment by Noroff-Anders** [comment]
It look like someone has already solved this. I cant see any issues with the search icon now. closing this
 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/299881de-3ee2-4f5c-a234-084bffd34b33)
