### ISSUE TITLE
Register form error for existing user should be more specific

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#606]
- The error message should specifically state that the error is that the user already exists. 

<img width="458" alt="Screenshot 2024-01-10 at 11 46 02" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/fda1b128-9c18-4baf-8cc4-eea609815c37">

**Comment by LineNil** [comment]
Was fixed by another dev.
