### ISSUE TITLE
Footer || different spacing on the footer columns

### ISSUE THREAD

**Issue by Knirkeli** [NoroffFEU/agency.noroff.dev#620]
Lots of text in the first column, causes the second to have different gap to the lef then the rest of the columns.
#

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/6482dcf8-fd61-48ab-ad35-b4fb98d4c98d)

**Comment by Knirkeli** [comment]
Lots of text in the first column, causes the second to have different gap to the lef then the rest of the columns.
#

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/f76cfbd3-5922-40b4-ba08-bf6ab1ac8b87)

**Comment by Sugal99** [comment]
It seems like the title is the cause of this problem, you can solve this by, using "text-nowrap" on the title element.

**Comment by KristianNilsenAug22FT** [comment]
PR closed for this issue as it is handled in #654 
So this issue can be closed
