### ISSUE TITLE
Form containers || Brakepoint and size on different screen sizes

### ISSUE THREAD

**Issue by Knirkeli** [NoroffFEU/agency.noroff.dev#623]
The containers for the forms have strange size differences on different screen sizes.

The sizing of the content in the form container and the form container should be polished to make the form more consistant.

Big screen:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/7fa99f01-2393-40bd-bb16-5ac1e3767ffd)

Smaller screen:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/ee038383-ac16-47e2-bb0a-33454ae81622)

**Comment by runeunhjem** [comment]
Goes under styling - assigning Team Tryvann as they have styling in Sprint 2

**Comment by Bekkholt** [comment]
This is done and moved to QA.

**Comment by KristianNilsenAug22FT** [comment]
PR reviewed and approved
