### ISSUE TITLE
Duplicate id's : navItems

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#629]
There are duplicate id's in here (navItems):
Fix this, but be careful tu update any other code that reference this either by getElementById or querySelecor("#navItems")

export const checkState = () => {
  const role = localStorage.getItem('Role');
  const navBarNav = document.getElementById('navbarNav');
  if (role == 'user') {
    return (navBarNav.innerHTML = `<ul class="navbar-nav gap-2" id="navUl">

    <li class="nav-item">
      <a class="nav-link text-white fw-semibold" aria-current="page" href="/index.html" id="navItems">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-white fw-semibold" aria-current="page" href="/pages/user/index.html" id="navItems">Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-white fw-semibold" href="/pages/listings/index.html" id="navItems">Listings</a>
    </li>
    <li class="nav-item">
      <a class="btn btn-outline-light text-white fw-semibold" href="#" id="signOut">Log out</a>
    </li>
  </ul>`);
  }

**Comment by runeunhjem** [comment]
remember to also update css files to match your solution in index.js


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/3578d5c8-9154-4a1e-b99e-10f8a18dbb49)

**Comment by Tokle89** [comment]
I have now finished the task anc created a pull request.
All the nav items now have an id that matches their Href`s
f,eks: nav-item that links to the home page has an id called : "navHome".

Have also updated the id tag in scss, to their classname instead of the id.
So in _header.scss  they all called by class name : "nav-link"

Link to pull request: https://github.com/NoroffFEU/agency.noroff.dev/pull/635

**Comment by bLangved** [comment]
Just want to mention that this is allready technically part of the #345 I am working on. 
I have allready rewrote the whole index.js not to use innerHTML, but rather use mode secure modern syntax, and the js is modularized into smaller segments as well. 
I could integrate the id's you have named into my code if that is cool?

**Comment by runeunhjem** [comment]
QA just want to look over and check if no trouble will arise first
But ok by me if ok by him.

**Comment by bLangved** [comment]
Trying to add all issues regarding header in one issue alone, since there are multiple cases of conflicting issues (lots of people working on small segments of the header code). 

#672 Is the issue for all things related to the header

**Comment by runeunhjem** [comment]
So you just close this ticket when you are ready and done :)
