### ISSUE TITLE
Update / add link to Figma Wireframes

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#649]
In useful-information.md:
Link now goes to Experimentation - OLD

HiFi Wireframes:
https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=0%3A1&mode=design&t=CZ56opBRWy80vuGK-1

**Comment by runeunhjem** [comment]
Reassigning this to Tryvann as they have all styling in Sprint 2

**Comment by Bekkholt** [comment]
Link is updated.
