### ISSUE TITLE
Remove empty spaces in skills and about me in edit mode

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#650]
When editing profile, there is emty spaces in the beginning of the first line.
These should be removed.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/f449aad2-7ebc-45bd-8087-630c25463b73)

**Comment by elli95** [comment]
Removed the gap, it should be good now.

Pull request [#674](https://github.com/NoroffFEU/agency.noroff.dev/pull/674)
