### ISSUE TITLE
Convert footer innerHtml to use createElement

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#654]
js/ui/footer/index.js

export const footer is returning footer elements as innerHtml.

Change this to use createElement in stead for security reasons.

Be sure to use same classes and id's that are already in use so styling does not get broken

**Comment by Murots** [comment]
Should be good to go. See [PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/762)

**Comment by KristianNilsenAug22FT** [comment]
PR reviewed and approved
