### ISSUE TITLE
View More button on listings page doesn´t take you anywhere, it is not linked to single listing page

### ISSUE THREAD

**Issue by vanya992** [NoroffFEU/agency.noroff.dev#656]
When you press the button for view more nothing happens, it is not linked to any other page.

**Comment by runeunhjem** [comment]
Assigning to Team Holmenkollen wich will have listings Sprint 2

**Comment by AnaCascante** [comment]
This has to be assign to team vettakollen, we are in charge of buttons

**Comment by runeunhjem** [comment]
Reassigning to Holmenkollen - Will be taken when Fredrik is done with [Create functional listing page#756](https://github.com/NoroffFEU/agency.noroff.dev/issues/756)

**Comment by runeunhjem** [comment]
I'm guessing this falls in under what you are doing now @Tokle89 ?
Should I just close this ticket?

**Comment by Tokle89** [comment]
Yes, u can just close this ticket

**Comment by runeunhjem** [comment]
This issue is being handled here: [Create functional listing page#756](https://github.com/NoroffFEU/agency.noroff.dev/issues/756)

Closing ticket.
