### ISSUE TITLE
Show Student View Section if role is Applicant

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#659]
pages/user/index.html

Student view is hidden by default.
Make it show if localStorage role = "Applicant"

  <div class="d-none" id="studentView">

**Comment by Kobraz** [comment]
[Pull Request made #685](https://github.com/NoroffFEU/agency.noroff.dev/pull/685)



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/16524760/a7b5fb46-1169-48c7-80e9-6f0607c33947)

**Comment by runeunhjem** [comment]
This issue was not resolved by the end of Sprint 1, and has not been merged.
Issue may therefor if need arises be revisited next week during Sprint 2 by whomever would be working theme related to this.
