### ISSUE TITLE
Quotes on email when logging in

### ISSUE THREAD

**Issue by Christelmarita** [NoroffFEU/agency.noroff.dev#668]
Quotes are back on email when logging in after checking "remember me" on first log in.
<img width="476" alt="Screenshot 2024-01-11 at 11 29 36" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/114878235/406b08e3-e150-4064-9fb6-8b3bd91714bd">

Problem was first fixed in issue #528
<img width="640" alt="Screenshot 2024-01-11 at 11 31 41" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/114878235/88c9e6c7-a654-4943-b94b-6a14eddb07af">

Refractoring of code on issue #544 
<img width="1067" alt="Screenshot 2024-01-11 at 11 25 05" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/114878235/a59b06e7-dc82-409f-b75c-89feb1d90587">

Reverting of code on pull request #618 due to this issue
<img width="913" alt="Screenshot 2024-01-11 at 11 27 45" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/114878235/14813140-a055-47f8-ae83-0b068386d965">

New solution needed

**Comment by hah98** [comment]
You are right, the problem is back! Here is how it looks for me at the moment. (See image attached).

There seems to be a problem with how the users login information is stored, could this issue also be linked to the fact that the logout is not properly working? See issue #677

js/storage/storage.js 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/12cbe333-64e6-4406-b73f-61c1969adf1f)

**Comment by Christelmarita** [comment]
@hah98 Yes, the problem lies in how it´s stored, but It shouldn´t have anything to do with the logout button not working. But as @maleneivy noticed, the previous solution did break the retrieval of user role in Local Storage unfortunately. 
Regarding the log out button, I believe @bLangved is working on it and all things related to the header in issue #672 

I wonder if a solution to the quotes issue (without touching how it´s stored) could lie in setLoginFormListener.js with a change like this:
  if (storedEmail && emailInput) {
    // add const cleanedEmail to remove quotation marks from the stored email
    const cleanedEmail = storedEmail.replace(/['"]+/g, '');
    emailInput.value = cleanedEmail;
  }

**Comment by MHerholdt94** [comment]
Hello!

I believe this issue is part of #487

**Comment by bLangved** [comment]
@Christelmarita @MHerholdt94 I don't believe this is related to my issue #672 . 
My functions only work with the "role" item in localStorage. 

I do believe it is in regards to how the email item is either stored and/or retrieved. It might be stringified twice, or not parsed correctly?

**Comment by Christelmarita** [comment]
As per jan 12th the issue seems to have disappeared.
Ticket will be closed if the issue doesn´t return within the day.

**Comment by mathiasg12** [comment]
is someone working on this issue?

**Comment by Christelmarita** [comment]
@mathiasg12 Not at the moment. The issue seems to have been resolved due to some other change, at least here. Are you experiencing this issue still?

**Comment by mathiasg12** [comment]
yes I still have this issue last time I checked, wanted to create a new user to see if it still was an issue but cant log in at the moment

**Comment by Christelmarita** [comment]
I see! Then by all means, if you want to take on this issue and handle it once the login/registration function works again you´re more than welcome :)
