### ISSUE TITLE
Login/signup/forms - Links should have similar styling as footer links?

### ISSUE THREAD

**Issue by Knirkeli** [NoroffFEU/agency.noroff.dev#669]
The user experience would be better with some indication other then the pointer. Could be the same efect as the links in the footer, or could be styled to grow a bit, or change color. Will do some work and post screenshot here.

**Comment by Knirkeli** [comment]
Some small changes that uses the hoover styling on the footer

Without adding padding:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/3beaf912-8166-4e1d-a4f7-d972ff988cd9)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/62d7d84f-268d-4523-ac38-f08438da3259)


With added padding
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/6612ad07-9f7c-4723-a5ed-8e6ab54d0804)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/3ffd06fb-dba6-4231-8ac4-76f97cb1ac21)

code:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/282be203-6097-4804-83cd-7280e04c1e50)

**Comment by runeunhjem** [comment]
Assigning to Team Tryvann as they have styling Sprint 2
Please check with Kristine / Korketrekkeren to be sure as they have all login/registration Sprint 2

**Comment by Bekkholt** [comment]
Hover styling made and moved to QA.
