### ISSUE TITLE
Header - HTML, styling & script 

### ISSUE THREAD

**Issue by bLangved** [NoroffFEU/agency.noroff.dev#672]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/101604131/1608ebec-f713-4d4e-b791-2ed6368c8a31)

### What this issue address:
- HTML elements
- CSS/SCSS custom styling / bootstrap classes
- Js scripts in regards to the header (creating html and checking user state / dynamic changes to html based on user state)

**Open tasks:**

- [x] Improve responsiveness on all screen sizes
- [x] Swap existing Noroff logo-solution with new logo file @Pgarza-dev fixes logo
- [x] Register and login / logout buttons changes alignment so slightly between 970-980px 

**Collective tasks**
- [x] Figure out to structure branching on this issue

**Bjørnar**

- [x] Refactor original js from innerHTML to use createElement
- [x] Modularize header/index.js into seperate js files
- [x] Log out the user when using the logout-button
- [x] Make the navigation dynamicly change to reflect user role
- [x] Implement correct hrefs on links based on user role 
- [x] Improve accessibility on the entire header (ARIA++) #806 
- [x] Clean up project board issues related to Header (see issues listed above - and if there are more). If issues are not listed below, add a subtask

**Mathias**
- [x] remove bootstrap which makes the header bigger at md breakpoint
- [x] add padding or margin to main so content dont overlap with header
- [x] New logo implemented (by whom?), and the paddings on the sides are off. Hamburger also breaks at about 320px (300px should be target). This is implemented on main-branch, not this branch.
- [x] make login and register the same size
- [x] make the currently on element bold: so if a user is currently on the home page the home page in nav is bold

**Michael**

- [x] Change _log out_ from _link_ to _button_ and update to correct styling
- [x] Fix _hamburger toggler_ to display and to be light color #784 
- [x] Hamburger menu icon, animation and correct breakpoint
- [x] Remove margins on _navbar_ and _logo container_
- [x] Adjust nav and list element styling on all sizes - _could use some padding on the **ul  element**. for ex. **p-2 p-md-0**_

If anyone has questions in regards to Header related issue, please leave a comment, and tag @bLangved .

**Comment by bLangved** [comment]
#345 - Please look at this issue

**Comment by Christelmarita** [comment]
I see issue #658 pertains to this also, maybe it should be closed?

**Comment by bLangved** [comment]
@Christelmarita Added a comment, and assigned myself to it. Thx for telling me :)

**Comment by RiverMichael** [comment]
#784 is live, Hamburger toggler is fixed, the animation will come in a later update!
