### ISSUE TITLE
Logout button not working as intended

### ISSUE THREAD

**Issue by hah98** [NoroffFEU/agency.noroff.dev#677]
The logout button (both in the header and hamburger menu(mobile) is not working as intended. 

The only way I could logout properly was to go into Application and manually clear the local storage. No errors show up in the console. 

Looking through the code I suspect that the logout functions created have not been added properly. 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/e9ebb7a7-265e-4e63-81e8-22e6bc6230b0)
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/c9ee8fa7-da97-417b-bf6c-3948133b3feb)

**Comment by AnaCascante** [comment]
@jonnebonde Hi, I see that you took this issue from me, and now removed yourself, Then I can take back the issue for my team?

**Comment by kribac12** [comment]
@AnaCascante should this go to the header team now? @chalund is SM :)

**Comment by RiverMichael** [comment]
This problem has already been solved. 

- The button works in the current version.
- The correct styling update is coming in #672
