### ISSUE TITLE
User can't edit profile properly

### ISSUE THREAD

**Issue by hah98** [NoroffFEU/agency.noroff.dev#679]
At the moment it's not possible to edit profile avatar and other information such as skills, about me, title etc. When I try to edit profile I get the error in the image. 

I also remember trying to add an avatar when I was creating the profile, is anyone else experiencing this? 

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/c7bf54ee-4e0c-4084-ad3d-75b8b266a4f8)

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/649142ec-1ee5-45be-b1bd-f16dcc790b08)
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/9b8d9a5a-65d4-4d7c-93e5-acfee322a858)

**Comment by AnaCascante** [comment]
I added your group  for this issue :) Have fun solving the issue 😊

**Comment by hah98** [comment]
It is now possible to edit the users profile with information and avatar etc. 

However when the user clicks edit profile the profile information that has previously been updated should show up and populate the form. 

Right now it shows up empty like the image attached shows. (I have successfully added information to my profile, check image 2). 
And if the user just clicks update without putting in any new information the profile goes back to being blank, as if they have never given any profile information. This is if the user refreshes the page or leaves and comes back. 


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/e7ed3a8d-9793-451f-ade6-1a7946018929)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/74331454/22d3da39-cc38-4c2b-9ccf-72f594dfd9da)



How can we solve this issue?

**Comment by KevinHavn** [comment]
There are a couple of issues for the lack of pre-population, for instance [751](https://github.com/NoroffFEU/agency.noroff.dev/issues/751), and [752](https://github.com/NoroffFEU/agency.noroff.dev/issues/752).

**Comment by KevinHavn** [comment]
Closing since issue seems to have been fixed - prepopulation should probably be fixed in new issues, ask scrum master if unsure.
