### ISSUE TITLE
Listing page, status 200 but there is an error

### ISSUE THREAD

**Issue by nyolarraklay** [NoroffFEU/agency.noroff.dev#680]
the response in not define in the getListOfListings.js, 
HTML is link to _allListingPage.scss.
set width of searchBar to auto

**Comment by nyolarraklay** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/682

**Comment by Sovak3441** [comment]
PR did not pass build test.

Build-log; https://github.com/NoroffFEU/agency.noroff.dev/actions/runs/7501697864

**Comment by Sovak3441** [comment]
The issue causing it to fail have been resolved by another fix. To have this pr resolve, it needs to have it's file updated to the current version.
Please update files, and push so it can be closed

**Comment by nyolarraklay** [comment]
done- resolved
