### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by Sugal99** [NoroffFEU/agency.noroff.dev#699]
Login seems fine, but whenever you try to login on as an applicant or company, it does not work.

It responds with this Console error:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/56642911/166402ff-b458-4cec-aaee-bd1ea63e7cae)

**Comment by kimrm** [comment]
This is already taken care of in https://github.com/NoroffFEU/agency.noroff.dev/issues/661 

It's pending QA.

**Comment by sulenchy** [comment]
@Sugal99 and @kimrm, Can you confirm you can create a company on production? I keep responding with a 404 status code, and the request payload does not look correct 

```
{
    "imageUrl": "https://postimg.cc/McgjFTpw"
}
```

I think there is a need to investigate the registration functionality.

**Comment by kimrm** [comment]
@sulenchy 

Yes, registration for applicants seems to work, but for a company, it does not. It's a different error than the one mentioned in this issue's description though. I agree it should be investigated, but maybe it should be added as a new issue that addresses the actual error?

**Comment by runeunhjem** [comment]
Closing this as it has been resolved as mentioned by Kim above here
This is already taken care of in https://github.com/NoroffFEU/agency.noroff.dev/issues/661
