### ISSUE TITLE
Terms of use page is not found

### ISSUE THREAD

**Issue by Queenen** [NoroffFEU/agency.noroff.dev#717]
<img src="https://i.imgur.com/gc5Yvq5.png">

**Comment by runeunhjem** [comment]
Assigning this to Hans after speaking to him as this is a vite issue

**Comment by Spookyrumble** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/745

**Comment by runeunhjem** [comment]
PR closed and merged - all good
