### ISSUE TITLE
Privacy policy page is not found

### ISSUE THREAD

**Issue by Queenen** [NoroffFEU/agency.noroff.dev#718]
<img src="https://i.imgur.com/xc9pVS2.png">

**Comment by runeunhjem** [comment]
Assigning this to Hans after speaking to him as this is a vite issue

**Comment by Spookyrumble** [comment]
Fixed in PR 745: https://github.com/NoroffFEU/agency.noroff.dev/pull/745

**Comment by Spookyrumble** [comment]
Closing this. See issue 717.
