### ISSUE TITLE
Profile page Alt Attribute for default Avatar

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#737]
**Web view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/5015175f-a838-42d9-a227-0e9e16ccab8a)

**Description:**
 
We have identified that the alt attribute for the default user avatar image in the profile page (`pages/user/index.html`) is not descriptive enough for accessibility purposes. The current implementation does not adequately describe the image when a default avatar is used, which is crucial for screen reader users and overall web accessibility. This issue aims to update the alt attribute to provide a more accurate description of the default avatar.

**Task:**

1. Review the `renderProfileImage` function in `src/js/templates/profile/userDetailsTemplate.js`.
2. Implement a check to determine whether a default avatar is being used.
3. Update the alt attribute to "Default User Avatar" or a similar descriptive phrase when a default avatar is displayed.
4. Ensure that the alt text update is consistent across both company and user profiles.
5. Test the implementation to ensure that it does not affect other functionalities.

**Acceptance Criteria:**
- The alt attribute for the default avatar image should accurately describe the image as "Default User Avatar" when no custom avatar is provided.
- The implementation should be consistent for both user and company profiles.
- The update should not introduce any regressions or bugs in the profile page functionality.
- The solution should be tested across different browsers to ensure compatibility.
- The change should comply with web accessibility standards, enhancing the experience for users relying on screen readers.

**Comment by runeunhjem** [comment]
Seems this has already been handled:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/17d30c40-9d9d-45c8-87ff-56cd6fc2f5dd)

**Comment by Sugal99** [comment]
@runeunhjem Its being displayed as "Unknownavatar" right now:



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/56642911/90ba3ccf-7240-48c3-a5d0-792961ef1f09)


And its because of this: 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/56642911/89f5c5a7-f177-4d70-84f2-44b48cadaab4)

So, I think ill just change it to be bit more descriptive such as "Default User Avatar" instead.

**Comment by Sugal99** [comment]
Pull request:
[#737](https://github.com/NoroffFEU/agency.noroff.dev/pull/978)
