### ISSUE TITLE
Profile page h1 font with Design Specification

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#738]
**[Design](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=139%3A1358&mode=design&t=suMCTmmQzq9njRId-1) view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/8668b69f-0bc1-47b3-a734-eafec7205118)

**Web view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/bd001a10-426d-4a3e-8360-46f7f37427a1)

**Description:**

There was a discrepancy between the font used for the `h1` element between the design specification and the current website implementation. The design specifies using the Halcon font for the `h1` elements, but the website currently uses the Livvic font for all headings (`h1` to `h6`) and body. This inconsistency affects the visual consistency and branding of the website. The goal of this issue is to update the `h1` font to meet design specifications while keeping the rest of the headings and body text consistent with the current implementation.

**Task:**

1. Review the current SCSS implementation for the font family in the headers and body.
2. Update the SCSS to use the "Halcon" font for `h1` elements, ensuring that it overrides any existing styles.
3. Test changes on different browsers and devices to ensure compatibility and responsiveness.
4. Review the design to ensure it matches the intended visual style.

**Acceptance Criteria:**

- `h1` elements on the site should use the "Halcon" font as specified in the design.
Changing the font should not affect the layout or responsiveness of the website.
- The updated font should be visually consistent across browsers and devices.
- The implementation must be approved by the development team to ensure it is consistent with the overall vision of the project.
- A clear decision on whether the typography fix will be applied only to the company profile and pages or extended to the entire application.

**Comment by Ninuskaninus** [comment]
Pull request: https://github.com/NoroffFEU/agency.noroff.dev/pull/829
