### ISSUE TITLE
Profile page profileRole font with Design Specification

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#741]
**[Design](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=139%3A1358&mode=design&t=suMCTmmQzq9njRId-1) view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/8cc25a0d-62f6-49e7-a918-dbe089104a35)

**Web view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/1c6eb1af-cbdf-4d34-8a94-df6e5d599e16)

**Description:**

There is a mismatch between the font used for the `<p id="profileRole" </p>` element in the design specification and the current website implementation. The design specifies using the Halcon font for this element, but the website is currently using the Livvic font for all headings (h1 to h6) and body. This inconsistency affects the visual consistency and branding of the website. The goal of this issue is to update the font to meet design specifications while keeping the rest of the headings and body text consistent with the current implementation.

**Task:**

1. Review the current SCSS implementation for font family in headers and body.
2. Update SCSS to use the "Halcon" font for this element, ensuring that it overrides any existing styles.
3. Test changes across different browsers and devices to ensure compatibility and responsiveness.
4. Review the design to ensure it matches the intended visual style.

**Acceptance Criteria:**

- `<p id="profileRole" </p>`  elements on the site should use the "Halcon" font as specified in the design.
Changing the font should not affect the layout or responsiveness of the website.
- The updated font should be visually consistent across browsers and devices.
- The implementation must be approved by the development team to ensure it is consistent with the overall vision of the project.
- A clear decision on whether the typography fix will be applied only to the company profile and pages or extended to the entire application.

**Comment by zalacop** [comment]
I think this issue has been sorted already when the issue #738 was done. The font is already being applied to the body. But if it's needed, I can specifically add the #profileRole after body.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/103320914/0acaa696-4a28-4c11-b494-3a227bd26612)

**Comment by zalacop** [comment]
Added a screenshot that the font is being applied.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/103320914/30230c15-660f-4ab5-9733-1e77d74f7b04)
