### ISSUE TITLE
Profile page Remove Hard-Coded Skills List from Profile

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#744]
`pages/user/index.html` **view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/32f4beba-f714-45b2-ad8a-502b11db49e2)

**Web view**:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/9495844b-f154-4d85-b3a0-1d540f2dfb8d)

**Description**: 
In the current implementation of the user profile page, there is a hard-coded list of skills under the `skillsList` element. This static list does not reflect the actual skills associated with the user and is not dynamically generated from the backend. The goal of this issue is to remove the hard-coded skills and ensure that the skills list is populated dynamically from the API, providing an accurate representation of the user's skills.

**Task**:
1. Identify and remove the hard-coded list of skills in the `skillsList` element within `pages/user/index.html`.
2. Ensure that the `skillsList` element is prepared to dynamically render skills fetched from the API.

**Acceptance Criteria**:
- The hard-coded skills list is removed from the `skillsList` element in the user profile page.
- The user profile page remains visually consistent and functions correctly after the removal of the hard-coded list.
- The changes are tested across different browsers and devices for consistency.

**Comment by emilrh91** [comment]
Finished the task, should be working. Made  a [PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/833)
