### ISSUE TITLE
Profile page Implement Applications Listing Section

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#746]
**[Design](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=139%3A1358&mode=design&t=suMCTmmQzq9njRId-1) view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/70a98a09-af6f-4306-8899-36d810d0791a)

**Web view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/2a52f0af-abb0-48bc-83ea-710300cefa0d)

**Description**: 
We have identified that the "Applications Listing" section, which is an integral part of the design, is currently missing from application. This section is crucial for displaying a list of applications, providing users with necessary information and functionality. The absence of this section leads to a gap in user experience and functionality as envisioned in the design. The purpose of this issue is to implement the "Applications Listing" section according to the design specifications to ensure consistency and fulfill user expectations.

**Task**:
1. Review the design specifications to understand the intended layout, style, and functionality of the "Applications Listing" section.
2. Create the necessary HTML structure for the "Applications Listing" section in the appropriate page(s).
3. Style the section to match the design, ensuring responsiveness and consistency with the overall application's look and feel.
4. Conduct thorough testing to ensure that the section is functional, responsive, and aligns with the design specifications.

**Acceptance Criteria**:
- The "Applications Listing" section is implemented as per the design specifications.
- The new section is fully responsive and visually consistent with the rest of the application.
- The implementation is tested across different browsers and devices for consistency.

**Comment by Christelmarita** [comment]
Static HTML created as example of how page should look. 
Cannot add function to fetch applications and offers until users can apply for jobs and complies can offer jobs.
HTML is to be recreated with createElement, not innerHTML, when aforementioned functions exist.

**Comment by Christelmarita** [comment]
@KevinHavn PR is ready at https://github.com/NoroffFEU/agency.noroff.dev/pull/892
