### ISSUE TITLE
Profile page Implement Favourite Listings Section

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#747]
**[Design](https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=139%3A1358&mode=design&t=suMCTmmQzq9njRId-1) view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/4c6d7778-487e-4f56-b90a-bbc9dc5630a7)

**Web view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/2a52f0af-abb0-48bc-83ea-710300cefa0d)

**Description**: 
We have identified that the "Favourite Listings" section, which is an integral part of the design, is currently missing from application. This section is crucial for displaying a list of applications, providing users with necessary information and functionality. The absence of this section leads to a gap in user experience and functionality as envisioned in the design. The purpose of this issue is to implement the "Favourite Listings" section according to the design specifications to ensure consistency and fulfill user expectations.

**Task**:
1. Review the design specifications to understand the intended layout, style, and functionality of the "Applications Listing" section.
2. Create the necessary HTML structure for the "Favourite Listings" section in the appropriate page(s).
3. Style the section to match the design, ensuring responsiveness and consistency with the overall application's look and feel.
4. Conduct thorough testing to ensure that the section is functional, responsive, and aligns with the design specifications.

**Acceptance Criteria**:
- The "Favourite Listings" section is implemented as per the design specifications.
- The new section is fully responsive and visually consistent with the rest of the application.
- The implementation is tested across different browsers and devices for consistency.

**Comment by zalacop** [comment]
I made an example of how the favourite card HTML should look. At the moment I'm not able to add listings to favourite.
@KevinHavn  I made a PR [#747](https://github.com/NoroffFEU/agency.noroff.dev/pull/905)
