### ISSUE TITLE
Register form - Remove one register button from Register for Applicants 

### ISSUE THREAD

**Issue by AnaCascante** [NoroffFEU/agency.noroff.dev#748]
- In the register for applicants there are two buttons for register in the same form
- Remove one of the buttons --> Buttons should be red with white text, according to the prototype. 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/4cf37c8f-6170-47ff-abba-770137efb839)

**Comment by kribac12** [comment]
@KarenBonillaM @AnaCascante 
Should Korketrekkeren take this issue, or have you completed it? :-)

**Comment by EM-90** [comment]
@kribac12 I did this when removed the duplicated add sign in task #775 so i dont think this task is necessary.

**Comment by AnaCascante** [comment]
@kribac12  should this issue be closed then?

**Comment by kribac12** [comment]
@AnaCascante @EM-90  closed the issue.
