### ISSUE TITLE
Edit Profile page Fix Avatar URL Error

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#749]
**Web view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/47c7dc79-8377-4b2d-9c0c-ee57ceda877e)

**Console:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/2bca0977-908e-441e-b44e-1f29532c3de6)

**Network:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/07a8ebe8-40ce-4f4d-b5d0-9f681496bd17)

[Noroff Agency API](https://agency-api.noroff.dev/api-docs/#/Application/get_application)

**Description:**
An error has been identified when users attempt to update their avatar URL in the "Edit Profile" modal. Specifically, a 400 Bad Request error occurs when the `editStudent` function in `src/js/api/users/editStudent.js` sends a PUT request to update the user profile. This issue affects the user experience by preventing successful profile updates and needs to be resolved. The objective is to troubleshoot and fix the error related to updating the avatar URL to ensure a smooth and functional profile editing process.

**Task:**
1. Investigate the cause of the 400 Bad Request error in the `editStudent` function when updating the avatar URL.
2. Ensure the avatar URL input field in the "Edit Profile" modal (`pages/user/index.html`) correctly captures and sends the URL.
3. Modify the `editStudent` function to handle the avatar URL update correctly, including appropriate error handling and validation.
4. Test the updated functionality to confirm that users can successfully update their avatar URL without encountering errors.
5. Implement any necessary changes to improve the overall reliability and user experience of the profile editing process.

**Acceptance Criteria:**
- The error causing the 400 Bad Request response when updating the avatar URL is identified and resolved.
- Users can successfully update their avatar URL in the "Edit Profile" modal without encountering errors.
- The `editStudent` function correctly processes and validates the avatar URL input.
- The profile editing process is tested for functionality and reliability.
- The user experience of updating profile information, including the avatar URL, is smooth and error-free.

**Comment by Sugal99** [comment]
Seems like this is already fixed by somebody else, since its working now.
