### ISSUE TITLE
Edit Profile page Pre-Populate Edit Profile Modal input Last Name with API Data

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#752]
**Before view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/ed7e2469-949c-4055-972e-873e7f3231ec)

**After view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/f73e80e8-fa60-47ea-96cc-5a6d21301cb2)
**_Example._**

**Description:**

Currently, when the "Edit Profile" modal opens, the input fields, including the `name=lastName` field, are not pre-populated with the user's existing data from the API. This can lead to a less intuitive and efficient user experience, as users have to re-enter their information even if they only want to make minor changes. The goal of this issue is to modify the "Edit Profile" modal so that it fetches and displays the user's current data from the API when opened. This enhancement will improve the user experience by providing a more seamless and convenient way to update profile information.

**Important:**

**_This field is required, the user cannot leave this field blank or use symbols or numbers._**

**Task:**

1. Modify the JavaScript logic associated with opening the "Edit Profile" modal to fetch the user's current profile data from the API.
2. Ensure that the modal correctly handles and displays data, including cases where some data might be missing or undefined.
3. Test the updated modal to ensure that it accurately displays the user's current profile data and allows for successful updates.
4. Validate the changes with users or the design team to ensure the functionality meets user experience standards.

**Acceptance Criteria:**

- The "Edit Profile" modal automatically fetches and displays the user's current data from the API when opened.
- The `name=lastName` input field, in the modal, are pre-populated with the user's existing data.
- The modal handles missing or undefined data gracefully, without causing errors or incorrect displays.
- The user can successfully update their profile information using the pre-populated modal.
- The implementation is tested and verified for functionality and user experience.

**Comment by bettytro** [comment]
I have started & finished work on this and #751  - but I don't have any rights to move it to the correct folder or to assign it to myself. I will create a PR and submit it for QA when we have the rights sorted out. I would suggest not working on it until it's in order.

**Comment by KevinHavn** [comment]
Moving back from Quality Assurance to Doing on the board as I can't find a pull request for this issue.

**Comment by MaxMartinsen** [comment]
@bettytro  Could you please open a pull request for this issue?

**Comment by MaxMartinsen** [comment]
PR https://github.com/NoroffFEU/agency.noroff.dev/pull/985
