### ISSUE TITLE
Edit listing function

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#757]
Should open a modal of the listing containing current content
see listings/listing/edit/index.html

make PUT request 
https://agency-api.noroff.dev/listings/{id}

Postman example:
https://agency-api.noroff.dev/listings/7533e4ca-9877-432b-9897-202d6b883b74

Figma:
https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=135%3A2329&mode=design&t=nfyMWd8SqhnbZQhM-1

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/e1e25846-d3cf-4b9c-808b-1a777cf2daae)

**Comment by elli95** [comment]
Currently the listings/listing/edit/index.html form contains additional input/value (location and cover img) that is not part of the [Api Documentation](https://agency-api.noroff.dev/api-docs/#/Listings/put_listings__id_).
However, it is missing the input/value tags and description from the Api Documentation.

Will add/remove input to correspond with the Api Documentation.

**Comment by elli95** [comment]
I've updated the layout to match the api documentation. 
Moved the edit listing forum into a modal at "pages/listings/listing/index.html".
Furthermore, I have edited and written further on the js codes for editing listings. 
I think I cover most of what I need here, but need to test it a bit more.

Currently missing:
- A function that displays the listings current values on opening.
- Success message

**Comment by elli95** [comment]
Added a function to displays the listings current values on opening. 
And added a success message, when successfully editing a post.
Rewrote the PUT request in editSingleListing.js, it shuld work now.

**Comment by elli95** [comment]
Pull request [#842](https://github.com/NoroffFEU/agency.noroff.dev/pull/842)

**Comment by runeunhjem** [comment]
Mergeconflicts resolved - closing issue
