### ISSUE TITLE
Create new listing

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#759]
Make function for creating new listing when you are logged in as client/company
Until the company profile page has been made, use this page:
pages/listings/listing/create/index.html and make function to create new listing with that form.
(We need a functional company/client account to actually create a new listing wich we right now do not have)

NOTE IN FILE:

          

See here:
pages/listings/listing/create/index.html (Edit to match input fields from api)
API:
```
{
  "company": "a120a09d-5td2-4eb1-8724-407fb13a8694",
  "title": "Looking for Front-end developer",
  "tags": [
    "front-end",
    "hiring"
  ],
  "description": "string",
  "requirements": [
    "html",
    "css",
    "javascript"
  ],
  "deadline": "2023-04-16T12:19:48.625Z"
}
```
pages/TBD/listings.html
src/js/listeners/post/createListing.js (Use this file and edit where needed.)

Should open as modal with correct inputs when New listing button is clicked.
UNTIL COMPANY PROFILE PAGE IS MADE - USE THE pages/listings/listing/create/index.html TO SHOW FORM
See company-profile-desktop(company view) in Figma

Figma:
https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=135%3A2329&mode=design&t=nfyMWd8SqhnbZQhM-1

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/bb094265-1ecf-4eac-81e6-5beb7cb5b1d9)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/163be5d4-5bdd-4e67-9645-b98cc8df3d98)

**Comment by Olekrr** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/878
A PR is now open for this issue
