### ISSUE TITLE
Test - verify change in header when user is logged out

### ISSUE THREAD

**Issue by Queenen** [NoroffFEU/agency.noroff.dev#761]

**Comment by Queenen** [comment]
The test is finished. PR is found <a href="https://github.com/NoroffFEU/agency.noroff.dev/pull/862">here</a>.
Waiting for QA to approve of changes.

**Comment by KristianNilsenAug22FT** [comment]
reviewed and approved PR

**Comment by Queenen** [comment]
I've merged the changes, closing this issue now.
