### ISSUE TITLE
Change job listing card on listings/index.html to match figma

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#764]
This may overlap with Fredriks ticket #655 (Crossreference with @Tokle89 before starting this)
Listings cards should be displaying only logo, text, applicants, date, and view more button

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/0db4c2b7-6bf8-4eff-9e00-0069c87ae6c8)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/02592734-ed4f-409c-80dc-70908dc22432)

**Comment by runeunhjem** [comment]
Need to add max-height/max-width to logos so they are all the same size no matter the size of the image added as logo by company/client on registration.

Need to set a fixed height to the cards so they are all the same height no matter what the content is

**Comment by runeunhjem** [comment]
@rebekkanordheim This one could go under styling if Tryvann need the work?
Make logo's same size with max values independent of original size.
Make the cards the same size independent of conten using min & max values

**Comment by Queenen** [comment]
I've been working on this for some hours, but I keep running into the same error using vite's build preview.  

EPERM: operation not permitted, lstat '\\?
✓ built in 13.98s
error during build:
Error: EPERM: operation not permitted, lstat '\\?
    at lstatSync (node:fs:1662:3)
    at rimrafSync (node:internal/fs/rimraf:180:13)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at fixWinEPERMSync (node:internal/fs/rimraf:304:5)
    at rimrafSync (node:internal/fs/rimraf:200:14)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    
   This obstacle has grown into a significant challenge for me, so I'm passing the torch to anyone who feels prepared to tackle it.
