### ISSUE TITLE
Create functional search on listings page

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#765]
Create a functional search on the listings page

**Comment by EkaterinaNattrass** [comment]
The function is added, some old code that is not used anwhere deleted. An onkeyup event, as there's no button to click. The search looks for the same characters in the listings titles. The search starts working with two characters in the input (as it's the minimal coherent piece of input from my point of view). If the input gets deleted, the search returns all the listings visible on the webpage.

**Comment by runeunhjem** [comment]
Pull request:
adds search listings functionality #851
