### ISSUE TITLE
Create functional filter function on listings page

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#766]
Make filter functions that corresponds with the 4 dropdown options
Should filter the listings on the page relative to what filter is being selected.

**Comment by EkaterinaNattrass** [comment]
The filtering function lets users filter the listings on cllick based on the following filters:
- all(renders all the listings)
- latest (latest 4 days)
- 14 days
- 30 days

**Comment by runeunhjem** [comment]
Pull request: adds search listings functionality #851
