### ISSUE TITLE
Header- Add username on header when logged in

### ISSUE THREAD

**Issue by YngvN** [NoroffFEU/agency.noroff.dev#768]
I feel that would look more professional

**Comment by idanguyen** [comment]
No access to figma file. delay until next release.

**Comment by chalund** [comment]
This is an idea from the prototype in [figma](https://www.figma.com/file/hWJsAz3LDOfLmoYag2zvPS/dekstop-vesrion-for-editing?type=design&node-id=0-1&mode=design&t=W4qIVJJ48ihwXIQ3-0)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114383740/bbf32612-aae5-407e-90e3-23c72f6f2ffc)
