### ISSUE TITLE
Header overflows Main

### ISSUE THREAD

**Issue by kimrm** [NoroffFEU/agency.noroff.dev#770]
Header element overflows main. Probably because of the fixed-top css class. Either Main needs more margin or Header should not get fixed-top before scrolling.

**Comment by chalund** [comment]
The Kolsås team is working on the issue.

**Comment by EM-90** [comment]
I think there is a easy fix for the Header. Just change the bootstrap class to "sticky-top" instead of fixed. But this will make the position of header relative i think, so when opening the hamburger menu on a smaller screen the content on the page will be pushed down. @chalund
