### ISSUE TITLE
Buttons - Add a more distinct color change on hover

### ISSUE THREAD

**Issue by Sovak3441** [NoroffFEU/agency.noroff.dev#771]
On hover over the buttons, the color changes are very faint, and may be hard for visual impaired to see. And there is no other effect to show.
- Make the hover effect more distinkt
- Add other effects on hover to make it more clear the button is being hovered

**Comment by Murots** [comment]
[PR ](https://github.com/NoroffFEU/agency.noroff.dev/pull/1027)

**Comment by KristianNilsenAug22FT** [comment]
commented and approved PR
