### ISSUE TITLE
WCAG Landing page

### ISSUE THREAD

**Issue by Spookyrumble** [NoroffFEU/agency.noroff.dev#772]
Lighthouse Accessibility test:

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/93d41fc6-e7b0-4941-a031-68d4e084e43d)

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/c87cbcd0-13fa-485b-9036-07561102ac83)

![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/90a540a8-6ee2-447e-8ffb-6273679fa447)

**Comment by KarenBonillaM** [comment]
Issues fixed. 

Alt text in the logo has been added


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/e8b13a33-c21e-413d-b710-e3e463ca648d)

Contrast errors were fixed



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/0a2c5515-264a-404b-a97a-94978e5e638f)



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114474341/19073f09-27e6-4751-ac12-0b236cccd39c)
