### ISSUE TITLE
Make hardcoded cards use same classes on listings page

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#773]
pages/listings/index.html

```
<!-- dummy-cards start -->
          <div class="card bg-theme-light shadow col-12 col-md-5 m-2"> 
            <div class="mt-5 px-2 thumbnail-img card-img-top img-fluid img-thumbnail">  WRONG

```
Should be:
```
<!-- dummy-cards start -->
          <div class="card bg-theme-light shadow col-12 col-md-5 m-2"> 
            <div class="mt-5 px-2">  SAME AS THE OTHER 3 CARDS

```

**Comment by Tokle89** [comment]
Since the cars are being rendered, maybe the dummy cards should be deleted instead?   for cleaning up the html files, and because they serve no purpose

**Comment by runeunhjem** [comment]
Your right, but if someone by error delete or mess up the fetching, it is ok to have this as backup.
So until finished with doing listing work, I think it is warranted to have it there.

**Comment by runeunhjem** [comment]
Status here @mariajaro ?

**Comment by mariajaro** [comment]
working on it! PR coming later today

**Comment by runeunhjem** [comment]
Pull request #977
https://github.com/NoroffFEU/agency.noroff.dev/pull/977

**Comment by runeunhjem** [comment]
I see there has been done a lot of changes that is not mentioned as the task here.
This can be closed without merge as I will delete the dummy cards for SEO optimization purposes.

Closing ticket and making new ticket for dummy cards deletion.
