### ISSUE TITLE
"Show more" on registration form "Register as applicant" needs to be explicit and moved

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#775]
- "Show more" + icon for adding another degree is placed below "Register for company" link, and it is not apparent what it is for before clicking it
- Also, when clicked to add a new input for degree, the + icon is still shown below "Register for company link", and another one is added next to the new input field, but when clicking on the one next to the new input field the input field disappears. 

<img width="366" alt="Screenshot 2024-01-15 at 10 13 19" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/9d0509ed-5f42-4e66-a78b-877000d8027f">
<img width="572" alt="Screenshot 2024-01-15 at 10 13 32" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/1b339aaf-26fd-4e0f-b1ab-fb7ff2065f93">

**Comment by EM-90** [comment]
I can take a look at this ;) @kribac12

**Comment by kribac12** [comment]
![Screenshot 2024-01-15 at 12 05 15](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/bd85f28e-ea81-4b2d-a684-a73cc89be864)
@EM-90

**Comment by EM-90** [comment]
It is ready for QA @Psijii

**Comment by Psijii** [comment]
Commented on the PR
