### ISSUE TITLE
Register and login forms titles not visible for certain screen sizes, pushed behind header

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#776]
- Top of the forms should be visible for all screen sizes.  
- Talk to SM @chalund in case her team has done something with the header that has affected these changes.

<img width="822" alt="Screenshot 2024-01-15 at 10 20 18" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/1c01870b-ed26-44b7-b163-9b537796fcb5">
<img width="554" alt="Screenshot 2024-01-15 at 10 20 32" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/cb357149-7254-4b0d-ba35-23a14ec30732">
<img width="789" alt="Screenshot 2024-01-15 at 10 20 49" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/a1150cef-4546-4759-ad16-44a1e5661740">

**Comment by chalund** [comment]
The kolsås team is working on the issue.

**Comment by kribac12** [comment]
@chalund Great, I will close this issue.
