### ISSUE TITLE
Grammar - Register for companies "Register as a applicant" add "an" instead of "a" 

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#782]
- Register as a applicant ---> should be "Register as an applicant"

![Screenshot 2024-01-15 at 11 12 42](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/615539f6-25bd-4325-abac-7d9c0cf38795)

**Comment by mhaarseth** [comment]
I'm on it!

**Comment by mhaarseth** [comment]
I am still running into the issue I had about differences in formatting, when creating the pull request. I've not been using prettier when working on my own, but VSCode's own formatter. I thought I'd fixed it last week, but now it's back. Will go back and try fixing it again before making a new pull request.

**Comment by mhaarseth** [comment]
Fixed.

PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/793

@Psijii

**Comment by Psijii** [comment]
Nice find! 
Commented on the PR.
