### ISSUE TITLE
Register form "Register as applicant" validation styling, error messages

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#783]
- The error messages created last week needs to be styled to make it clear that they are error messages prompting user to redo their inputs. 

![Screenshot 2024-01-15 at 11 21 26](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/185938f2-0343-48fa-a434-9f8775c835fa)

**Comment by ellie489** [comment]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114486930/34942c50-f7cf-4697-a753-118c6f3c477a)

I decided to use styling with classes is-valid and is-invalid, and the current css file has classes for invalid feedback as well. However, I think the text is too small and the color is too vague. Im stuck on making the next choice. Do I change the css file and risk ruining other invalid feedback elements on the page? Do I make my own styling for the register form or do I just keep it as is? Can someone help? @NoroffFEU/korketrekkeren

**Comment by EM-90** [comment]
Use this page https://webaim.org/resources/contrastchecker/ to find out if the color is wcag compliant, if it is leave it as it is now (looks good buy the way). I can take a look at the css to help you find a solution

**Comment by ellie489** [comment]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114486930/71f05a26-0dfe-4f7e-8919-a89cc398b9ff)

Thank you! As suspected, the contrast is far from good enough, so I need to make some changes. I found the form validation colors from the style guide, and will implement this. 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114486930/fbe7bafd-95dd-4033-a768-dbbea92bb4c2)

**Comment by ellie489** [comment]
Im not sure why, but when I change the colors in src/scss/index.css, the styles doesn't change in the css file. Can someone help @NoroffFEU/korketrekkeren ? Am I editing the wrong file?

**Comment by LineNil** [comment]
Working on this

**Comment by ellie489** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/888 This PR is ready for QA @Psijii

**Comment by kimrm** [comment]
PR #888 approved and merged.
