### ISSUE TITLE
Investigate JS error for register form "Register for company"

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#788]
- JS errors when the form is submitted. There's an error message in console: TypeError: Cannot read properties of null (reading 'replace')
![Screenshot 2024-01-15 at 12 00 34](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/29556e46-46b9-4db4-be32-df3e1c0ab049)

**Comment by kimrm** [comment]
The reason for this specific error message is a missing token. This occurs if a user is not logged in. Company registration requires authenticating with a token. This issue is part of a bigger refactoring and restructuring, thats needed, for the whole company registration process.

**Comment by kimrm** [comment]
This is related to issue #815 

Closing this issue.
