### ISSUE TITLE
Register form consistent titles adhering to the same rules for use of capital letters

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#789]
- Register For Applicant should say "Register for Applicant" OR "Register for applicant", and "Register For companies" should say "Register for Companies" OR "Register for companies", and needs to follow the same rule chosen for the applicant title. 

![Screenshot 2024-01-15 at 12 02 42](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/83609e95-830c-4aa4-8741-6b0e14f957e6)
![Screenshot 2024-01-15 at 12 02 51](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/5b74f74b-3dc4-4cb4-bfba-5ec8b836d24b)

**Comment by Psijii** [comment]
Commented on the PR
