### ISSUE TITLE
Login form validation 

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#791]
- Login form should have immediate validation, especially for email(ex: "Please use a valid E-mail address"). 
- _Validation for password: Password should be at least five characters, according to the form. **Register for applicant form says 8 characters, they should not differ. Check out API.**_ 
Confirmed to be five characters (See comments below), and the HTML validation for this is correct for the login form. The validation function in validateInputs.js requires 8 characters for the registration form, as well as the HTML validation. Will make a separate issue regarding fixing this.

- For now, validation shows only when clicking "Log in", and then it only refers to the password unless I have not written one or more characters in the email input. 
- If I write a long enough password, it says "Invalid login credentials. Please try again", even if I have written "wfe" as an email and this could be pointed out earlier. 

![Screenshot 2024-01-15 at 12 17 12](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/8232ecf1-02ed-403d-82f7-72eded5afd04)

![Screenshot 2024-01-15 at 12 15 04](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/e5b9c9f3-ed16-4310-bd91-678619fd2dac)

![Screenshot 2024-01-15 at 12 17 45](https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/32ae7c4a-b357-43f5-ab1f-4974e6f164d9)

**Comment by kribac12** [comment]
@NoroffFEU/korketrekkeren available issue.

**Comment by mhaarseth** [comment]
I can give this one a shot, @kribac12!

**Comment by mhaarseth** [comment]
Thank you @ellie489, I'll take a look at it!

**Comment by mhaarseth** [comment]
I was unsure if I would be able to continue working on this task after all my trouble digging through the code, but during this mornings stand up meeting, @NoroffFEU/korketrekkeren  encouraged me to go on. I'll use this as a learning opportunity, giving myself the time I need to practice reading others' code, while still communicating issues and asking for assistance along the way. Go team!

**Comment by mhaarseth** [comment]
@NoroffFEU/korketrekkeren Testing using the API docs (https://agency-api.noroff.dev/api-docs/#/Users%20Authenticate/post_users), it seems five characters is the required number of characters in the password. I make this assumption based on the response from the server when using the "Try it out" function in the documentation. Using four characters ("1234") it responds with "Invalid value in password field(s)". Using 5 characters ("12345") it responds with the next error, making me interpret that as the character limit being 5, and thus correct in the login form, but wrong in the registration form.

**Comment by ellie489** [comment]
So the character limit should be 5 in the registration form as Well? Or 8 in both?

**Comment by mhaarseth** [comment]
@ellie489 - It should be five in both, as far as I can tell.

**Comment by ellie489** [comment]
Okay, I think you can go ahead and create a new issue for this for the registration form. Or We can discuss in team group tomorrow If You prefer.

**Comment by mhaarseth** [comment]
I'll make a new issue after the stand up meeting tomorrow.

**Comment by kribac12** [comment]
@mhaarseth sounds good, Magnus.

**Comment by mhaarseth** [comment]
I have recruited @EM-90 to be on call for answering my questions and confirming my assumptions for today. Go team!

Could you check to see if you agree that setLoginFormListener.js is the file I should start using for building the login form validation?

**Comment by EM-90** [comment]
@mhaarseth I am looking at what you wrote on issue now. you might as well start in setLogginFormListener. I also see that there is a file called validateInputs.js . In this file there are functions that you can reuse in setLogginListener Will look into it a bit more, so we can find some good solutions

**Comment by mhaarseth** [comment]
Thank you, @EM-90! in validateInputs they check the the email against a regex- pattern, but at the point the user is logging in they must already have passed this test, so would you consider it necessary to check against the pattern a second time? The way I see it, the only email related validations the login form must check for (when the field loses focus, I reckon) is that the email field contains a valid e-mail address, in case the user mistyped or forgot a character etc., and then, on submit, if the user exists. If the user is not registered, it does not matter if its a noroff email or not, they will be prompted to register  a new user, and in the register form they will be informed that they need a noroff email. What do you think?

**Comment by EM-90** [comment]
@mhaarseth After a user has registered, the user can log in, but if the user should enter the wrong e-mail (not very likely but can happen) they will not receive a feedback, unless you create a completely new validation instead of reusing what already exists. validateEmail() checks against the reg ex pattern as you say, and if it is not correct you get this message errorDiv.textContent = 'Invalid email address. Use a valid noroff.no or stud.noroff.no email.';. I'm not quite sure if I understand you correctly, but if the user is not registered, it doesn't matter if it's a noroff email or not, I totally agree with you there, but before a user gets that message ( "The user does not exist"), the user must actually write an email address that macthes the reg ex pattern so it is checked by the API. I think you check the reg ex pattern when you register, but also when you log in. But the reason I thought you could use the validate functions that have already been created is because it's easier to reuse it, because it's the validation error message we're going to highlight. Hope some of this made sense

**Comment by EM-90** [comment]
If you want you can send me some of the code, or we can look at it together @mhaarseth

**Comment by EM-90** [comment]
@mhaarseth you had a very good suggestion about using help text, by doing this I think you can prevent the user from making mistakes immediately. As long as the help text is short and concise, it should be good. The only thing that you have to create is an error message if the user does not exist.  I have used this myself. This is not the best example but here is one 



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/94170154/169c67e8-627b-4a5f-b369-8c0d0d5bab6e)

**Comment by mhaarseth** [comment]
@NoroffFEU/korketrekkeren Still working on this, at current I have succeeded in using the already built validation function in validateInputs.js for the registration form, to give user feedback on inputting an invalid email. Should I work on styling as well, if time, or should that be a separate issue?

**Comment by mhaarseth** [comment]
@EM-90 @kribac12 Added password validation in the same way as for the email, took only five minutes now having understood the code. As discussed earlier, the validation function for this sets the required number of characters to eight, and not five, as the server does. Seeing as this originates from a function used by multiple forms, I guess fixing this should be a new issue?

**Comment by mhaarseth** [comment]
PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/945

@Psijii

**Comment by Psijii** [comment]
@mhaarseth I get a conflict:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111748314/e1f80e29-eee2-4eaf-a80f-140598677fb8)

Not sure if I want to touch it then.

**Comment by mhaarseth** [comment]
Did you look at the conflict? It's four lines, where someone else added a single parameter to the function. I can resolve it myself it you need me to, just wanted your opinion on it first. (As I've stated in my edited comment above).

**Comment by Psijii** [comment]
If you know what you're doing, resolve it! I've checked it out, and tbh I feel like a noob.

**Comment by mhaarseth** [comment]
@Psijii Should be good to go now :)

**Comment by Psijii** [comment]
Commented on the PR
