### ISSUE TITLE
Center footer in desktop sizes

### ISSUE THREAD

**Issue by JeanArce** [NoroffFEU/agency.noroff.dev#802]

**Comment by Murots** [comment]
Related to this: [](https://github.com/NoroffFEU/agency.noroff.dev/pull/762.) Although the left alignment of text do make the last column appear a bit off.

**Comment by JeanArce** [comment]
Check this pull request [https://github.com/NoroffFEU/agency.noroff.dev/pull/841](https://github.com/NoroffFEU/agency.noroff.dev/pull/841) Please do QA, thanks

**Comment by JeanArce** [comment]
The current footer is not really centered properly, there are more spaces in the right, which seems for me, its not good to look at especially in desktop sizes

**Comment by JeanArce** [comment]
Setting it back to QA

**Comment by KristianNilsenAug22FT** [comment]
commented and approved PR
