### ISSUE TITLE
Fix background of both "Sign in" and "Register" form - whit gap above footer

### ISSUE THREAD

**Issue by EM-90** [NoroffFEU/agency.noroff.dev#808]
As You can see the background of both "Sign in" and "Register" has a gap between the bottom of the form and the footer. Task: remove the white spacing displayed on the images

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/94170154/2b057111-5ef2-4f30-8d96-159ec5bb5828)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/94170154/e84c00bc-bc02-47db-8ba8-66adf52e3e87)

**Comment by mhaarseth** [comment]
Just so you know, this gap does not show up using Firefox, so be sure to check that your fix works there as well, and doesn't introduce new errors @EM-90

**Comment by EM-90** [comment]
I think i have a solution that will make it so that it looks good in all browsers, but i have to do this tomorrow. But thanks for the heads up ;)

**Comment by EM-90** [comment]
@Psijii   https://github.com/NoroffFEU/agency.noroff.dev/pull/906

**Comment by Psijii** [comment]
Commented on the PR
