### ISSUE TITLE
Edit Profile page Replace Title Field with Non-Editable Email

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#809]
**Before view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/120a9f2f-a509-4a4b-9eb9-5f1cd77f254e)

**After view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/d7e01d0d-936b-4a78-966e-6f772139d0b7)

**Task:**

- Replace the "Title" field with an "Email" field that displays the user's email.
- Ensure the "Email" field is non-editable and read-only to the user.
- Update the user interface to clearly indicate that the email field is not editable, adjusting styling as necessary to fit with the rest of the UI design.
- Test the implementation to ensure the email is displayed correctly and the field cannot be edited.
- Validate that this change does not negatively impact other functionalities of the application.

**Acceptance Criteria:**
- The "Title" field is successfully replaced with the "Email" field in the specified location.
- The displayed email is accurate, corresponding to the user's account information.
- The "Email" field is clearly marked as non-editable and read-only.
- The updated field integrates seamlessly with the existing UI design.
- The application's functionality remains intact, with no new issues introduced due to this change.

**Comment by Sugal99** [comment]
Pull Request:[ #809](https://github.com/NoroffFEU/agency.noroff.dev/pull/1024)
