### ISSUE TITLE
Company registration form - changes needed

### ISSUE THREAD

**Issue by kimrm** [NoroffFEU/agency.noroff.dev#815]
When creating a company we need to create a new user in the same process. Company registration requires authentication with token, and the user also needs to have the "Client" role set.

This is how the registration form looks like now:
<img width="767" alt="Skjermbilde 2024-01-16 kl  05 38 01" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/20448821/e45f4a02-2a31-497f-90f9-fca9e53a356d">

This is from the Figma prototype:
<img width="524" alt="Skjermbilde 2024-01-16 kl  05 34 01" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/20448821/225934f1-98d0-411f-95b2-061d5b214db1">

The password and e-mail form fields should be added to the form and the registration functionality should include creating a new user with the "Client" role.

**Comment by kimrm** [comment]
@Psijii

**Comment by Psijii** [comment]
Commented and reviewed on the PR
