### ISSUE TITLE
WCAG - Profile (logged in)

### ISSUE THREAD

**Issue by Spookyrumble** [NoroffFEU/agency.noroff.dev#819]
Identical ID's and header elements not in descending order.
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/24240ed1-6c46-4c5a-a1e9-eecd79944eab)
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/e4290ea8-0901-4ab4-a88f-2c967d5227af)

**Comment by MHerholdt94** [comment]
Closing this issue, as the tasks is handled by another team/other teams
