### ISSUE TITLE
WCAG - Policy and Terms

### ISSUE THREAD

**Issue by Spookyrumble** [NoroffFEU/agency.noroff.dev#821]
https://agency.noroff.dev/privacy_policy.html
https://agency.noroff.dev/terms_of_use.html

Same issues on both pages: 

ID repeat and header order:
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/e8167042-4c0c-4f4d-aa18-10bd78218ba7)
![image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114398900/58ef1e99-5b25-4a82-9e82-1b3491639a39)

**Comment by Chrissebah** [comment]
It would seem that whatever issues were causing the items to not load are now fixed. As for the heading elements I have not changed it from being h4 to h3 as that could make pages that contain a h3 look weird. So I will just move this to done. By all means contact me if it is desireble that I change this :)
