### ISSUE TITLE
Listings page - content not centered on smaller devices

### ISSUE THREAD

**Issue by Beatevangsnes** [NoroffFEU/agency.noroff.dev#822]

**Comment by Beatevangsnes** [comment]
<img width="509" alt="Skjermbilde 2024-01-16 kl  09 48 26" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/112164771/76805511-9f9a-4d23-9c26-29ea6c8faf37">

**Comment by Miksel90** [comment]
@rune59 @rebekkanordheim 

Hey, not realy sure which team should have this. 
Resposiveness on all browsers on the listing page.

**Comment by rebekkanordheim** [comment]
Maybe my team Tryvann?

**Comment by Miksel90** [comment]
sure, ill give it to Tryvann then =)

**Comment by Bekkholt** [comment]
Done and moved to QA.

**Comment by KristianNilsenAug22FT** [comment]
Commented and approved PR
