### ISSUE TITLE
Searchbar on listings page - does not look right

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#824]
Need to change it up a little

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/20ad7617-5bed-47ae-b591-15a306a97d54)

Add rounded corners, a mall drop shadow, white input field, and maybe if you can - another light color as input bg on focus (when someone is typing in it)
Use bootstrap classes / custom scss

**Comment by Kobraz** [comment]
Pull Request [#834](https://github.com/NoroffFEU/agency.noroff.dev/pull/834)

Added 'rounded' and 'bg-white' to class, like this: class="form-control rounded bg-white"
