### ISSUE TITLE
WCAG - Register Page

### ISSUE THREAD

**Issue by nyolarraklay** [NoroffFEU/agency.noroff.dev#830]
![Skjermbilde 2024-01-16 112037](https://github.com/NoroffFEU/agency.noroff.dev/assets/114483893/344a7c18-6a42-463f-bbde-9a5a87d1b569)

Some issues to correct:
1. Contrast Error
2. Empty Buttons
3. skipped heading
4. orphaned form

**Comment by nyolarraklay** [comment]
PR # https://github.com/NoroffFEU/agency.noroff.dev/pull/908

**Comment by Sovak3441** [comment]
Completed and Merged
