### ISSUE TITLE
Profile page Remove Unwanted Shadows on Skills List and About Me Sections

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#845]
**Design view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/50ff9e74-1794-47d8-9013-9ad8ed17d4a5)

**Local view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/b7183604-24f5-4afe-a618-268af20f2e79)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/8671a34e-f374-4c08-95e2-eae7e18669cb)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/786b46be-1b08-4995-b570-6d858a7ba54c)

**Description:**
It has been noted that the "Skills list" and "About Me" sections on the profile page currently have shadows, which deviate from our original design prototype. According to the design specifications, these sections should not have any shadow effects. The presence of these shadows affects the visual consistency and adherence to the design guidelines. This issue aims to correct the styling by removing the shadows from these sections.

**Tasks:**

1. Identify and locate the SCSS styles or classes responsible for the shadow effects on both the "Skills list" and "About Me" sections in the profile page.
2. Remove or modify the SCSS properties (such as box-shadow) that are adding the shadow effect.
3. Ensure that the updated styling matches the design prototype, with no shadow effect on these sections.
4. Test the changes in different browsers and screen sizes to ensure that the removal of the shadow does not affect the layout or responsiveness of the page.

**Acceptance Criteria:**

- The "Skills list" and "About Me" sections on the profile page do not have shadow effects.
- The updated styling is consistent with the design prototype and design specifications.
- The removal of the shadow effect does not negatively impact the layout or responsiveness of the page.
- The implementation is tested across different browsers and devices for consistent appearance.

**Comment by emilrh91** [comment]
Finished the task, should be working. Made a [PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/876)
