### ISSUE TITLE
Footer | Customer service link in footer is not linked to any page

### ISSUE THREAD

**Issue by vanya992** [NoroffFEU/agency.noroff.dev#854]
There is no page that it could be linked to

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/6277d04d-9461-49b9-b9c2-ae2d6286b63c)

**Comment by maleneivy** [comment]
Removed link in [PR 867](https://github.com/NoroffFEU/agency.noroff.dev/pull/867) ☺️
