### ISSUE TITLE
Footer | Privacy policy link in footer is not linked to any page

### ISSUE THREAD

**Issue by vanya992** [NoroffFEU/agency.noroff.dev#855]
There is no page that it could be linked to

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/c20c0b71-0cad-4cdc-8608-aaac87f3c4e8)

**Comment by maleneivy** [comment]
This is handled in [PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/867) ☺️
