### ISSUE TITLE
Footer | Terms of use link in footer is not linked to any page

### ISSUE THREAD

**Issue by vanya992** [NoroffFEU/agency.noroff.dev#856]
There is no page it could be linked to 

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/73e2d126-1f21-438c-a8b1-4b4d0799f8a7)

**Comment by vanya992** [comment]
From Figma design page it is removed linking option so @maleneivy is removing it from actual page

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/aafcc7c6-ffd6-4138-a768-c4c7b68414c8)

**Comment by maleneivy** [comment]
This is handled in [PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/867) ☺️
