### ISSUE TITLE
Footer | Ad policies link in footer is not linked to any page

### ISSUE THREAD

**Issue by vanya992** [NoroffFEU/agency.noroff.dev#857]
There is no page that it could be linked to

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/0ea883f5-7049-4d65-a599-f1d7cf8b37a9)

**Comment by vanya992** [comment]
from Figma design it has been removed ad policies so linking option is not required, @maleneivy is removing it from the actual page as well

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111580069/4c43e2f1-8b3e-4207-afca-5f275afca181)

**Comment by maleneivy** [comment]
Removed link in [PR 867](https://github.com/NoroffFEU/agency.noroff.dev/pull/867) .

**Comment by Mariuskvaal** [comment]
as Vanya992 says: There is no page to link it to. And is has been removed. so there is nothing for me to do

**Comment by MariuszRozycki** [comment]
@Tanific @sulenchy @NoroffFEU/phoenix 
Thats right what @Mariuskvaal wrote in this comment over my one https://github.com/NoroffFEU/agency.noroff.dev/issues/857#issuecomment-2001941561.

I will move this assignment to DONE.
