### ISSUE TITLE
Profile - reworking scripts

### ISSUE THREAD

**Issue by chalund** [NoroffFEU/agency.noroff.dev#861]
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/101604131/b63ea489-8ae2-4da8-922c-1d77c62dc4a6)

### What this issue address:

Scripts inside src/js/template/profile is not working correctly, and they seems a bit messy. 
Will be refactoring and modularizing some code.

**Original developer comment in userDetailsTemplate:** 
// Author Truls Haakenstad @Menubrea
// Dev Team: Frontend - User
// To Future Developer
_I've tried to organize content in a matter that I believe should be easy to inherit. Don't expect any of this code to run, because it will certainly not. At the moment I'm writing this, the response object is still not finalized, so variables have been named more so based on familiary for you to understand and guesstimates based on available data and expectations._ 

_Conditional logic I would expect to require some tweaking, based on the 3 different views available. As of now there should be at least 3 different views - company(own), user(own) and profile(other). HTML is structured in in a way where there's #studentView and #companyView, both of these are hidden by default with 'd-none'. It's possible it would make more sense to extract the role from the profile response to apply your logic as opposed to a saved key in local storage._

_Any question can be forwarded to Truls H. Haugen in Discord, or @Menubrea on github.__

**Open tasks:**

**Collective tasks**
- [x] Figure out what to do, who does what, and how to solve whats broken

**Bjørnar** - Rendering profile page based on user role
- [x] Rework logic for retrieving and processing user object 
- [x] Rework logic in terms of rendering page based on role
- [x] Modularize code where needed
- [x] Rename scripts/functions to clearer indicate what they are doing
- [ ] Input values in the edit profile form (both Applicant & Client roles) does not update the corresponding properties at the object in the APi. 

**Pablo** - Edit profile forms to update Object
- [x] Adjust edit profile container to display correct form based on user role
- [x] Working on company form api request
- [x] fix issues with handleEditForm.js
- [x] fix issues with correct form display for the user in createInput.js
- [x] update showUserDetails function for correct company ID

More updates will come when all is figured out

**Comment by Pgarza-dev** [comment]
Has the original Profile branch been merged yet?

**Comment by bLangved** [comment]
> Has the original Profile branch been merged yet?

Not yet. Still solving some minor issues after "#861-profile-pablo" and "#861-profile-bjornar" merged into #861-profile branch. When these issues are fixed, and the profile page renders the page correctly for both Applicant and Client, it will be merged into the main-branch. Will get that fix today! :)

**Comment by sulenchy** [comment]
@Pgarza-dev Are you working on this? What is the update?
