### ISSUE TITLE
Header - responsiveness 

### ISSUE THREAD

**Issue by chalund** [NoroffFEU/agency.noroff.dev#866]
Improve responsiveness on all screen sizes
Task: Ensure consistent header size across all screens.
![Screenshot 2024-01-17 at 11 49 06](https://github.com/NoroffFEU/agency.noroff.dev/assets/114383740/057f03bd-7e02-443f-a2ce-86a6cbd1ef6f)
![Screenshot 2024-01-17 at 11 49 26](https://github.com/NoroffFEU/agency.noroff.dev/assets/114383740/aa99162a-cc1d-4b70-a24f-436a564b1557)
![Screenshot 2024-01-17 at 11 49 41](https://github.com/NoroffFEU/agency.noroff.dev/assets/114383740/76675ad5-885d-4899-9ac2-076e492ccc50)

**Comment by chalund** [comment]
this is done in issue #672

**Comment by Emel-H** [comment]
Hi,

after building and launching main branch to investigate this issue, I am not able to reproduce the same behavior. my header is always the same height and the log in button does not seem to change. please see screenshot:

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114482435/c83bf931-dc83-4ad7-b1a0-924ae6169d41)

**Comment by chalund** [comment]
@Emel-H  the issue has been resolved. If you review the comments above, you'll find that it was addressed in another related issue :)
