### ISSUE TITLE
Updated the documentation

### ISSUE THREAD

**Issue by AnaCascante** [NoroffFEU/agency.noroff.dev#869]
Update documentation files for this project. Clean up unnecessary files and get all documentation in one place. 
test 

- [x] #909
- [x] #910
- [x] #913
- [x] #921
- [x]  Update/remove files in documentation map
- [x] #992

**Comment by Spookyrumble** [comment]
#909 moved to QA

**Comment by Spookyrumble** [comment]
#913 moved to QA
