### ISSUE TITLE
Change h2 font size to 1.1rem when url includes "listings/index.html"

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#870]
Add a listener function that will set the H2 font size to be 1.1rem as long as url includes "listings/index.html"

**Comment by haiderf7** [comment]
On it.

**Comment by haiderf7** [comment]
Added a function to export and import in index.js inside listing/index.js

Moving it to QA so it can be checked if its done right.

**Comment by haiderf7** [comment]
the import off the function was imported to the wrong index.js i ahve now imported it to the right index.js wich is the root index.js

**Comment by runeunhjem** [comment]
This ticket has been outdated - has been fixed elsewhere as the H2 fontsize now shows correctly on the listings.
This ticket can be closed and working branch can be deleted.
PR #900  should be closed without merging.

In regard of issue #890 -> Sync repo and make new branch with only the #890 issue task.
@Olekrr @haiderf7
