### ISSUE TITLE
WCAG - Error handling

### ISSUE THREAD

**Issue by MHerholdt94** [NoroffFEU/agency.noroff.dev#873]
Improve error handling to be more consistent across the site

**Comment by MHerholdt94** [comment]
PR #874

**Comment by Sovak3441** [comment]
Please take a look at the build status -> https://github.com/NoroffFEU/agency.noroff.dev/actions/runs/7556716719/job/20606884996

I dont know if this is an "old" build error, or if your files needs updating.

**Comment by MHerholdt94** [comment]
The PR for this issue was merged yesterday, so I assume this issue can be closed? Unless there is something else that should've been done

**Comment by Spookyrumble** [comment]
Fixed with #874
