### ISSUE TITLE
Link view listing button to open single listing page with correct id

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#877]
Clicking View button on listings page should open the correct single listing page

Single listing page should use something like this
const urlParams = new URLSearchParams(window.location.search);
const listingIdParam = urlParams.get("id");

**Comment by runeunhjem** [comment]
Have been fixed when doing #756

**Comment by Tokle89** [comment]
i have completed this task on my ticket #756
