### ISSUE TITLE
Edit Profile page Pre-Populate Edit Profile Modal textarea Skills with API Data

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#893]
**Local view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/6144aaa6-ac32-4953-8e73-6926ff9ad39f)

**Description:**

Currently, when the "Edit Profile" modal opens, the textarea fields, including the `name="skills"` `id="studentSkills"` field, are not pre-populated with the user's existing data from the API. This can lead to a less intuitive and efficient user experience, as users have to re-enter their information even if they only want to make minor changes. The goal of this issue is to modify the "Edit Profile" modal so that it fetches and displays the user's current data from the API when opened. This enhancement will improve the user experience by providing a more seamless and convenient way to update profile information.

**Task:**

1. Modify the JavaScript logic associated with opening the "Edit Profile" modal to fetch the user's current profile data from the API.
2. Ensure that the modal correctly handles and displays data, including cases where some data might be missing or undefined.
3. Test the updated modal to ensure that it accurately displays the user's current profile data and allows for successful updates.
4. Validate the changes with users or the design team to ensure the functionality meets user experience standards.

**Acceptance Criteria:**

- The "Edit Profile" modal automatically fetches and displays the user's current data from the API when opened.
- The `name="skills"` `id="studentSkills"` textarea field, in the modal, are pre-populated with the user's existing data.
- The modal handles missing or undefined data gracefully, without causing errors or incorrect displays.
- The user can successfully update their profile information using the pre-populated modal.
- The implementation is tested and verified for functionality and user experience.

**Comment by emilrh91** [comment]
Its working on my end. 
[PR](https://github.com/NoroffFEU/agency.noroff.dev/pull/979)
