### ISSUE TITLE
Unit test for listeners/post/createListing.js

### ISSUE THREAD

**Issue by KarenBonillaM** [NoroffFEU/agency.noroff.dev#915]
Create Unit tests for the next files:

- [ ] Unit test for listeners/post/createListing.js
- [ ] Unit test for listeners/post/editListings.js

_Originally posted by @KarenBonillaM in https://github.com/NoroffFEU/agency.noroff.dev/issues/779#issuecomment-1898134059_

**Comment by kyrregjerstad** [comment]
both the createListing and editListings need some refactoring and cleanup before it's possible to test them efficiently. Out of scope for this sprint, leaving this for the next group working on this.
