### ISSUE TITLE
The label is messing with searchbar justification

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#929]
The label need to get hidden of screen or set to a width of 1px or some other variant to make it not mess with the placement of the searchbar.
Do not use d-none/display: none as that will hide it from screen readers.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/4a263fe1-2545-40ea-a028-774e1d0b6cee)

**Comment by runeunhjem** [comment]
@EskanderAmadov Please do not self assign tasks - Let me know what you are interested in and I will assign. If not I will lose oversight of what is being dane / Have been done etc.

Also whenever you are working a task, please comment here as you go and end the task with a comment with a link to the PR you have made before moving it to QA

**Comment by EskanderAmadov** [comment]
Oh, sorry. I didn't mean to do this. I was checking the board on my phone and probably pressed something wrong😬

**Comment by Bekkholt** [comment]
This is now done and being moved to QA.

**Comment by KristianNilsenAug22FT** [comment]
Commented on PR

**Comment by KristianNilsenAug22FT** [comment]
approved pr after changes
