### ISSUE TITLE
Delete all links to stylesheets (link rel)

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#931]
Remove the <link rel.... > tags from these 4 pages completly

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/8bae7068-0416-45b7-a839-6a9b3aa2f8fc)

**Comment by haiderf7** [comment]
On it :)

**Comment by haiderf7** [comment]
Removed the the stylesheets on the requested pages and moved to QA.


PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/941
