### ISSUE TITLE
Remove all references to /public

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#938]
Sync repo and do a search for /public 
Go through all the results - 31 at the time of image below.
All references/paths that contain /public (and anything in front like ../../ etc) should be removed

The result should be 
```
<img class="icon" src="../../../../public/assets/icons/close.svg" alt="" /> should be
<img class="icon" src="/assets/icons/close.svg" alt="" />

<img src="../../public/images/placeholder.png" class="card-img-top h-100" alt="Image 1"> should be
<img src="/images/placeholder.png" class="card-img-top h-100" alt="Image 1">
```
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/5101a8d7-c09a-43bc-802a-bb8186539cdf)

**Comment by elli95** [comment]
Removed all references to /public.
The only examples left are in the userTemplate.js file, and these were commented out.

**Comment by elli95** [comment]
Pull request [#944](https://github.com/NoroffFEU/agency.noroff.dev/pull/944)
