### ISSUE TITLE
Fill inn all missing alternative text

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#939]
Sync repo and do a search for alt=""
Give descriptive alternative text to all results - 16 at the time of image below

alt=""  should be  alt"Illustration of close icon"  for instance.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/533bd26d-e36a-4a06-94be-6582dd389345)

**Comment by runeunhjem** [comment]
Ready 4 u now @haiderf7 :)

**Comment by haiderf7** [comment]
On it :)

**Comment by haiderf7** [comment]
Added "alt" texts on images where its missing, moved to QA. 

PR: https://github.com/NoroffFEU/agency.noroff.dev/pull/958
