### ISSUE TITLE
Fix small error in editlistings.js

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#949]
Fix ssmall error in the editListings.js file (line 22). 
A function is called, but it is done in a way that all other html files also call this function.

**Comment by elli95** [comment]
The error should be fixed now 
I moved getListing Data(listing Url); into the function called by the html that needs it.

**Comment by elli95** [comment]
Pull request [#951](https://github.com/NoroffFEU/agency.noroff.dev/pull/951)
