### ISSUE TITLE
success modal will not currently open on successful editing.

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#952]
success modal will not currently open on successful editing.
@elli95 believe it is missing some code in the editSingleListing.js file

Wait until previous editlisting ticket has been merged before syncing and starting the task

**Comment by elli95** [comment]
Added necessary code to editSingleListing.js, and for button in listing/index.html

**Comment by elli95** [comment]
Pull request [#965](https://github.com/NoroffFEU/agency.noroff.dev/pull/965)
