### ISSUE TITLE
Move search and filter to correct case in index.js

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#953]
In the index.js line 61-62, I believe that the searchListings(); and filterListings(); should be under "case 'listings'" (line 66).
It causes errors on the lising/index.html page as it is now.

**Comment by elli95** [comment]
Moved searchListings(); and filterListings(); under "case 'listings' "

**Comment by elli95** [comment]
Pull request [#954](https://github.com/NoroffFEU/agency.noroff.dev/pull/954)
