### ISSUE TITLE
Profile page Remove Border-Radius from Card Element

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#955]
**Design view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/70b12aab-9085-4f2b-bf52-78550ef35d13)

**Local view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/bbd8841b-81ec-4b89-b634-4d22640c220f)

**index.css**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/caabebcb-ff34-4f4b-9d3e-741c73a58bd0)

**Issue Description:**

In our current implementation, the card element is styled with a border-radius `var(--bs-card-border-radius)`. However, this styling does not align with our established design specifications, which call for a card with no border-radius. To maintain visual consistency with the design, we need to modify the card's styling by removing the border-radius.

**Tasks:**

1. Identify all instances of the card element in the application that are currently styled with `var(--bs-card-border-radius)`.
2. Modify the CSS to remove or override the border-radius property for these card elements.
3. Ensure that the updated card styling is consistent with the design specifications and does not negatively impact the layout or functionality of the card.
4. Test the changes across different pages and components to ensure visual consistency and proper rendering.

**Acceptance Criteria:**

- The border-radius styling `var(--bs-card-border-radius)` is successfully removed from all relevant card elements.
- The updated card elements have no border-radius and are consistent with the design specifications.
- The removal of the border-radius does not affect the layout, functionality, or responsiveness of the card elements.
- The changes are visually consistent across different browsers and devices.

**Comment by Christelmarita** [comment]
@KevinHavn PR is ready https://github.com/NoroffFEU/agency.noroff.dev/pull/959
