### ISSUE TITLE
Edit Profile page Update Width of Name Input Group in Mobile Version

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#956]
**Local view now:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/3184ed87-8ed8-4204-8eb1-d69457e85aca)

**Local view after:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/c704cecc-4889-4639-8dba-7aeb99020b1d)

**`pages/user/index.html` view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/49ab964e-1073-4103-a096-36080d0f07ed)

**Description:**
In the current implementation of our application, the "Name input group" is styled with a width of 50% (`<div class="w-50 mx-auto">`). This styling is not optimal for the mobile version, where a full-width (`100%`) layout would provide a better user experience. To enhance usability on mobile devices, we need to update the width of the "Name input group" from 50% to 100% in the mobile version.

**Tasks:**
1. Locate the "Name input group" in the application's front-end code (`<div class="w-50 mx-auto">`).
2. Update the HTML or CSS to change the width from 50% to 100% (`<div class="w-100 mx-auto">`) for the mobile version. This may involve adding responsive CSS classes or media queries.
3. Ensure that the change only affects the mobile version and does not impact the layout on larger screens.
4. Test the updated layout on various mobile devices and screen sizes to ensure the input group takes the full width and is visually appealing.
5. Confirm that the change does not adversely affect other elements or functionalities of the page.

**Acceptance Criteria:**
- The width of the "Name input group" is updated to 100% in the mobile version.
- The change provides an improved user experience on mobile devices with a full-width layout for the input group.
- The layout remains unchanged and functional on larger screens (tablets, desktops).
- The updated layout is tested and works correctly across various mobile devices and screen sizes.
- No other page elements or functionalities are negatively impacted by this change.

**Comment by Christelmarita** [comment]
@KevinHavn PR is ready https://github.com/NoroffFEU/agency.noroff.dev/pull/964
