### ISSUE TITLE
Profile page Standardize Card Design in Offers/Application and Favorites Sections

### ISSUE THREAD

**Issue by MaxMartinsen** [NoroffFEU/agency.noroff.dev#960]
**Local view:**

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/c643f8dc-cd7a-4fe0-8966-ce79ea3cd787)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/111891491/08b6ad14-a82d-4adb-9d96-cb230688dea3)

**Issue Description:**

Have observed inconsistencies in the card design between the Offers/Application and Favorites sections of our application. To maintain visual consistency and a cohesive user experience, it is necessary to standardize the card design across these sections. This task involves ensuring that the cards in both Offers/Application and Favorites have identical styling, layout, and functionality.

**Tasks:**

1. Review the current card designs in both the Offers/Application and Favorites sections.
2. Identify differences in layout, styling, and functionality between the cards in these sections.
3. Update the CSS and HTML as needed to make the card designs identical in terms of size, color scheme, typography, spacing, and any interactive elements (like buttons or links).
4. Ensure that the standardized card design is responsive and maintains its layout and functionality across different screen sizes and devices.
5. Test the updated designs thoroughly to ensure consistency and functionality in both sections.

**Acceptance Criteria:**

- The cards in both the Offers/Application and Favorites sections have identical designs, including layout, styling, and functionality.
- The standardized design is responsive and works well across various devices and screen sizes.
- The update enhances the overall cohesiveness and user experience of the application.
- The changes are tested and verified to function correctly without introducing new issues.

**Comment by Christelmarita** [comment]
@KevinHavn PR is ready https://github.com/NoroffFEU/agency.noroff.dev/pull/1019
