### ISSUE TITLE
Remove all empty class properties

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#962]
Sync repo and search for class=""
Go through each result and remove the class="" from the element

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/df256545-2d25-42da-b63e-2c8bbb4072b7)

**Comment by EkaterinaNattrass** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/995

All the empty classes were deleted
