### ISSUE TITLE
Add renderListing() / renderListings() to correct case on index.js

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#963]
Someone moved these around, so not all functionality is there now. 
Add correct one(s) to correct case(s)

**Comment by elli95** [comment]
Copied renderListing();, deleteItem(); and editListingListener(); under case 'singleListing'
Also changed the name of renderListings(); under case 'listing': to renderListing();
Now both cases 'singleListing' and 'listing' have the same value underneath them.

**Comment by elli95** [comment]
Pull request [#966](https://github.com/NoroffFEU/agency.noroff.dev/pull/966)

**Comment by haiderf7** [comment]
I missclicked and moved it to done, moved it back now, sorry My phone is living its own life 😂
