### ISSUE TITLE
Fix pageredirect on "No ID on listing page"

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#968]
I also found something in the renderListing.js file that should be looked at.
Looks like the code sends you away from the page if the ID is missing, the problem is that it sends you to a page that doesn't exist.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/6eaec4b4-a3a4-4304-8b21-1e0930b5d502)

**Comment by elli95** [comment]
Changed '/listings.html' to '../index.html' on line 44

**Comment by elli95** [comment]
Pull request [#970](https://github.com/NoroffFEU/agency.noroff.dev/pull/970)
