### ISSUE TITLE
Fix favicon path and alt text on listings/listing/index.html

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#981]
Remove /public and add alt text to the favicon

```
const createBtnContainer = () => {
  const element = createElement("div", ["d-flex", "align-items-center", "gap-2", "my-3", "buttonContainer", ])
  const applyBtn = createElement("a", ["btn", "btn-theme-secondary", "text-uppercase", "w-100", "rounded-0", "applyBtn"], null , "Apply for job")
  applyBtn.dataset.auth = "applyForJob"
  const favIcon = createElement("img", null, null, null, null, "/public/assets/icons/heart-fav.svg")
  favIcon.style = "width: 30px"
  const favBtn = createElement("button", ["btn", "btn-theme-light"], [favIcon])
  favBtn.dataset.auth = "favoriteListing"
  element.append(applyBtn, favBtn)
  return element

}
```

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/1a576139-c1b4-47b9-b933-807035381a20)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/9988d30c-5cf3-4eb3-b581-9a11dda013f7)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/887dc30a-5735-4aaf-b213-38f8dc6cdca2)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/cc394858-aabb-40ca-be4e-fea045e8abb4)

**Comment by EkaterinaNattrass** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/999

The path is changed, the alt is added
