### ISSUE TITLE
Put Edit/Delete listing when role = "Client" in the correct place, and when role = "Applicant" they should be hidden

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#982]
Put edit / Delete buttons in the right place as shown in figma
Figma: https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=0%3A1&mode=design&t=yHXxdfPwy0msaNVb-1

Edit and delete should only show when logged in as Client and owner of the listing.
Should be hidden for any other role.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/e3999439-8f40-4635-8597-54ac4bd94408)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/55674d15-1a1b-475d-a952-6c1bc4f0578d)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/4addbd00-5fe9-46f1-b86c-f694d3fdaef9)

**Comment by elli95** [comment]
Removed buttons, small style/layout change on listing/index.html
Added edit and delete buttons on renderListing.js

**Comment by elli95** [comment]
There were some problems with the code that we don't have time to solve before this sprint ends.
To the next group that takes over this task, refer to previous comments and this [branch ](https://github.com/NoroffFEU/agency.noroff.dev/tree/%23982-Put-Edit/Delete-listing-when-role-%3D-Client-in-the-correct-place%2C-and-when-role-%3D-Applicant-they-should-be-hidden)for the code we worked on.
Good luck!

**Comment by MariuszRozycki** [comment]
Hi Abi @AbiyuTashoma I found your branch among all branches, but I think we should add link to your branch here on this ticket as people. And here should be add some description what was done. ;)

**Comment by MariuszRozycki** [comment]
@AbiyuTashoma  @NoroffFEU/phoenix 
The problem has been solved. When the user's role is 'Applicant', the 'Edit/Delete' buttons are hidden. Conversely, when the user's role is 'Client', the 'Delete/Edit' buttons appear. Visually, everything looks as expected, just like in the Figma sketch.
I will merge your work to phoenix team branch ;)
