### ISSUE TITLE
Hide Apply for job button on single listing page when logged in as client

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#987]
Apply for job button and heart shold be hidden when logged in as client.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/3bcebc3e-0060-4e54-b4bb-7bef7c6c04d1)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/0ebff64d-ef4c-4f35-aa8d-160b3d605760)

**Comment by Olekrr** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/1012 fixed
