### ISSUE TITLE
Clicking View Listing after Editing singel listing does not go to page with ID

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#988]
View listing button leads to https://agency.noroff.dev/pages/listings/listing/index.html
Should lead to https://agency.noroff.dev/pages/listings/listing/index.html?id=7525164d-a48a-46b9-a69b-90975e609159  (Or the correct id depending on what you are editing.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/267e65d2-563a-4949-acd6-7c116201b65e)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/abf77c7f-285e-4401-8563-6546175d8a4e)
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/a0f99e2e-97aa-4f70-9a4a-6c46718f1191)

**Comment by elli95** [comment]
Changed "a href" to "button" and added id on listing/index.html
Added addEventListener for button that reloads page on editListings.js

**Comment by elli95** [comment]
Pull request [#1006](https://github.com/NoroffFEU/agency.noroff.dev/pull/1006)
