### ISSUE TITLE
Company field does not fetch company when i am logged in as client on create new listing

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#991]
Should automatically fetch client id and the clients company info.
Extracted company ID should be used to get Company name and show in the Company input field

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/a020404c-36ae-48b9-a3cd-7c16c8a6081a)

**Comment by Olekrr** [comment]
Wasnt quite sure what the local storage key would be when I made the thing, so I put a placeholder:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/93515165/c786e1a7-d055-44aa-afc0-45482e8f149c)

Replacing that should resolve the issue

**Comment by Olekrr** [comment]
https://github.com/NoroffFEU/agency.noroff.dev/pull/1001 PR
